from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('app_setting',sa.Column('key',sa.Text(),primary_key=True),sa.Column('value',sa.Text(),nullable=False))
 op.create_table('campaign',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('slug',sa.Text(),nullable=False),sa.Column('name',sa.Text(),nullable=False),sa.Column('market',sa.Text()),sa.Column('active',sa.Integer(),nullable=False,server_default='1'),sa.Column('config_ref',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.Column('updated_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.Column('city',sa.Text()),sa.Column('state',sa.Text()),sa.Column('category',sa.Text()),sa.Column('description',sa.Text()),sa.Column('daily_queue_limit',sa.Integer()),sa.Column('status',sa.Text()),sa.UniqueConstraint('slug'))
 op.create_table('prospect',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('campaign_id',sa.Integer(),nullable=False),sa.Column('name',sa.Text(),nullable=False),sa.Column('email',sa.Text()),sa.Column('phone',sa.Text()),sa.Column('website',sa.Text()),sa.Column('social',sa.Text()),sa.Column('category',sa.Text()),sa.Column('normalized_category',sa.Text()),sa.Column('address',sa.Text()),sa.Column('city',sa.Text()),sa.Column('state',sa.Text()),sa.Column('zip',sa.Text()),sa.Column('status',sa.Text()),sa.Column('score',sa.Float()),sa.Column('raw_score',sa.Float()),sa.Column('grade',sa.Text()),sa.Column('queue',sa.Text()),sa.Column('ownership',sa.Text()),sa.Column('research',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.Column('updated_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.Column('sales_status',sa.Text(),nullable=False,server_default='NOT_CONTACTED'),sa.Column('notes',sa.Text()),sa.Column('booked_value',sa.Float()),sa.Column('last_activity_at',sa.Text()),sa.Column('contacted_at',sa.Text()),sa.Column('replied_at',sa.Text()),sa.Column('consultation_set_at',sa.Text()),sa.Column('booked_at',sa.Text()),sa.Column('external_key',sa.Text()),sa.UniqueConstraint('campaign_id','name','email'))
 op.create_table('run',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('campaign_id',sa.Integer(),nullable=False),sa.Column('run_id',sa.Text(),nullable=False),sa.Column('run_status',sa.Text()),sa.Column('dry_run',sa.Integer(),nullable=False,server_default='1'),sa.Column('qualified_count',sa.Integer()),sa.Column('daily_queue_count',sa.Integer()),sa.Column('deferred_count',sa.Integer()),sa.Column('research_count',sa.Integer()),sa.Column('ineligible_count',sa.Integer()),sa.Column('manifest_ref',sa.Text()),sa.Column('queue_artifact_ref',sa.Text()),sa.Column('started_at',sa.Text()),sa.Column('completed_at',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.UniqueConstraint('run_id'))
 op.create_table('queue_item',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('run_id',sa.Integer(),nullable=False),sa.Column('prospect_id',sa.Integer(),nullable=False),sa.Column('position',sa.Integer()),sa.Column('priority',sa.Text()),sa.Column('queue_type',sa.Text()),sa.Column('status',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.UniqueConstraint('run_id','prospect_id'))
 op.create_table('crm_state',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('prospect_id',sa.Integer(),nullable=False),sa.Column('sync_status',sa.Text()),sa.Column('hubspot_contact_id',sa.Text()),sa.Column('hubspot_company_id',sa.Text()),sa.Column('hubspot_deal_id',sa.Text()),sa.Column('association_verified',sa.Integer(),nullable=False,server_default='0'),sa.Column('last_synced_at',sa.Text()),sa.Column('metadata',sa.Text()),sa.UniqueConstraint('prospect_id'))
 op.create_table('upload',sa.Column('id',sa.Text(),primary_key=True),sa.Column('original_filename',sa.Text(),nullable=False),sa.Column('stored_reference',sa.Text(),nullable=False),sa.Column('file_type',sa.Text(),nullable=False),sa.Column('size',sa.Integer(),nullable=False),sa.Column('sheets',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')),sa.Column('expires_at',sa.Text()),sa.Column('status',sa.Text(),nullable=False,server_default='ACTIVE'))
 op.create_table('external_action',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('prospect_id',sa.Integer(),nullable=False),sa.Column('action_type',sa.Text(),nullable=False),sa.Column('metadata',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')))
 op.create_table('calendar_event',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('prospect_id',sa.Integer(),nullable=False),sa.Column('provider',sa.Text(),nullable=False),sa.Column('calendar_event_id',sa.Text()),sa.Column('event_url',sa.Text()),sa.Column('consultation_start',sa.Text()),sa.Column('consultation_end',sa.Text()),sa.Column('created_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')))
 op.create_table('email_activity',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('prospect_id',sa.Integer(),nullable=False),sa.Column('provider',sa.Text(),nullable=False),sa.Column('provider_message_id',sa.Text()),sa.Column('recipient',sa.Text()),sa.Column('subject',sa.Text()),sa.Column('sent_at',sa.Text(),nullable=False,server_default=sa.text('CURRENT_TIMESTAMP')))
 op.create_table('google_connection',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('access_token',sa.Text()),sa.Column('refresh_token',sa.Text()),sa.Column('expires_at',sa.Float()),sa.Column('scope',sa.Text()),sa.Column('status',sa.Text(),nullable=False,server_default='NOT_CONNECTED'),sa.CheckConstraint('id=1'))
def downgrade():
 for t in ['google_connection','email_activity','calendar_event','external_action','upload','crm_state','queue_item','run','prospect','campaign','app_setting']: op.drop_table(t)
