import React,{useEffect,useRef,useState} from 'react';
import {api} from './api';

export const navigationGroups=[{name:'Sell',pages:['Overview','Up Next','Add Prospect','Lead Generator','Daily Queue','Prospects']},{name:'Plan',pages:['Follow-Up / Schedule Hub']},{name:'Manage',pages:['Campaigns','Runs','Settings']}];
export const pageName=(p:string)=>p==='Follow-Up / Schedule Hub'?'Follow-ups':p==='Up Next'?'Start selling':p==='Runs'?'Run history':p==='Lead Generator'?'Find prospects':p==='Settings'?'Settings & appearance':p;
const palettes=[{id:'chrome',name:'Ocean',a:'#8fd3ff',b:'#4776ff'},{id:'violet',name:'Lavender',a:'#d6a8ff',b:'#7c3cff'},{id:'emerald',name:'Mint',a:'#79f2c0',b:'#00a878'},{id:'rose',name:'Rose',a:'#ffd1dc',b:'#c9798f'},{id:'gold',name:'Sunrise',a:'#ffe29a',b:'#ed8468'},{id:'ice',name:'Glacier',a:'#d9fbff',b:'#65cfe8'},{id:'crimson',name:'Berry',a:'#ff8b9a',b:'#d51f45'},{id:'dusk',name:'Dusk',a:'#f1abff',b:'#5da9ff'},{id:'coast',name:'Coast',a:'#82e2d6',b:'#698dff'}];
function stored(key:string,fallback:string){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function applyAppearance(theme:string,mode:string){const p=palettes.find(p=>p.id===theme)||palettes[0];const root=document.documentElement;root.dataset.kpTheme=p.id;root.dataset.kpMode=mode==='light'?'light':'dark';root.style.setProperty('--kp-theme-a',p.a);root.style.setProperty('--kp-theme-b',p.b);root.style.setProperty('--kp-theme-soft',`color-mix(in srgb, ${p.b} 12%, transparent)`);root.style.setProperty('--kp-theme-glow',`color-mix(in srgb, ${p.b} 20%, transparent)`);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',mode==='light'?'#f3f5fa':'#0d121c')}
// Apply before React paints, including before the user opens Settings.
applyAppearance(stored('kp-interface-theme','chrome'),stored('kp-interface-mode','dark'));

export function Appearance(){
 const [theme,setTheme]=useState(()=>stored('kp-interface-theme','chrome')),[mode,setMode]=useState(()=>stored('kp-interface-mode','dark')),[saved,setSaved]=useState('Changes save automatically on this device.');
 const choose=(t:string,m:string)=>{setTheme(t);setMode(m);applyAppearance(t,m);try{localStorage.setItem('kp-interface-theme',t);localStorage.setItem('kp-interface-mode',m);setSaved('Saved on this device.')}catch{setSaved('Applied for now. Your browser could not save this preference.')}};
 return <section className="card xp-appearance"><p className="xp-eyebrow">MAKE IT YOURS</p><h3>Appearance</h3><p>Choose your light and your colors.</p><div className="xp-mode" role="group" aria-label="Color mode">{['dark','light'].map(m=><button key={m} aria-pressed={mode===m} onClick={()=>choose(theme,m)}>{m==='dark'?'☾ Dark':'☀ Light'}</button>)}</div><div className="xp-palettes">{palettes.map(p=><button key={p.id} aria-pressed={theme===p.id} onClick={()=>choose(p.id,mode)}><span style={{background:`linear-gradient(135deg,${p.a},${p.b})`}}/><b>{p.name}</b>{theme===p.id&&<i aria-hidden="true">✓</i>}</button>)}</div><small role="status">{saved}</small></section>
}

export function Icon({name}:{name:string}){const paths:Record<string,string>={menu:'M4 6h16M4 12h16M4 18h16',home:'m3 10 9-7 9 7v11h-6v-7H9v7H3Z',plus:'M12 5v14M5 12h14',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',sell:'m9 5 7 7-7 7',calendar:'M4 5h16v16H4ZM8 3v4M16 3v4M4 10h16',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8M18 7a3 3 0 0 1 0 6M22 21v-3a4 4 0 0 0-3-4',queue:'M8 6h13M8 12h13M8 18h13M3 6h1M3 12h1M3 18h1',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2'};return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.sell}/></svg>}

function useDialog(ref:React.RefObject<HTMLDivElement|null>,close:()=>void){useEffect(()=>{const previous=document.activeElement as HTMLElement;const el=ref.current;el?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'&&el){const items=Array.from(el.querySelectorAll<HTMLElement>('button,a[href],select,input,textarea,[tabindex="0"]')).filter(x=>!x.hasAttribute('disabled'));const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);requestAnimationFrame(()=>{if(previous?.isConnected)previous.focus();else document.querySelector<HTMLElement>('.mobile-menu-btn')?.focus()})}},[])}
export function AppNavigation({page,onNavigate,onClose,onTour}:{page:string;onNavigate:(p:string)=>void;onClose:()=>void;onTour:()=>void}){
 const ref=useRef<HTMLDivElement>(null);useDialog(ref,onClose);const [group,setGroup]=useState(navigationGroups.findIndex(g=>g.pages.includes(page)));
 return <div className="xp-overlay"><div className="xp-backdrop" onClick={onClose}/><div className="xp-drawer" role="dialog" aria-modal="true" aria-labelledby="xp-nav-title" ref={ref}><div className="xp-drawer-head"><div><small>KIDPRODUCTIONZ</small><h2 id="xp-nav-title">Your workspace</h2></div><button aria-label="Close navigation" onClick={onClose}>×</button></div><div className="xp-nav-tabs" role="tablist" aria-label="Navigation sections">{navigationGroups.map((g,i)=><button key={g.name} role="tab" id={`xp-tab-${i}`} aria-controls={`xp-panel-${i}`} aria-selected={group===i} tabIndex={group===i?0:-1} onClick={()=>setGroup(i)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setGroup(next);document.getElementById(`xp-tab-${next}`)?.focus()}}}>{g.name}</button>)}</div><nav aria-label="Workspace">{navigationGroups.filter((g,i)=>i===group).map(g=><section key={g.name} role="tabpanel" id={`xp-panel-${group}`} aria-labelledby={`xp-tab-${group}`}><h3>{g.name==='Sell'?'Your daily workflow':g.name==='Plan'?'Keep in touch':'Your workspace tools'}</h3>{g.pages.map(p=><button key={p} aria-current={p===page?'page':undefined} onClick={()=>{onNavigate(p);onClose()}}><span>{pageName(p)}</span><span aria-hidden="true">{p===page?'•':'›'}</span></button>)}</section>)}</nav><button className="xp-tour-link" onClick={()=>{onClose();onTour()}}>New here? Take a quick tour →</button></div></div>
}
const steps=[{page:'Overview',title:'Everything starts here.',text:'Pick your campaign at the top. The Overview gives you the shortcuts, progress, and calendar for your day.'},{page:'Lead Generator',title:'Find your first prospects.',text:'Search for the businesses you want to work with. Review the results before adding them to your campaign.'},{page:'Add Prospect',title:'Met someone in person?',text:'Add their name and a phone number or email. Notes are optional. They stay in your campaign for review.'},{page:'Up Next',title:'One conversation at a time.',text:'Start selling opens your next queued prospect. Call or draft a message, then save what happened. You confirm external sends and calendar changes.'},{page:'Follow-Up / Schedule Hub',title:'Always know the next step.',text:'Update follow-up times and notes here. Open prospect details to schedule a consultation, or preview and confirm a reschedule.'},{page:'Settings',title:'Make this your workspace.',text:'Choose Light or Dark and a color mix. Your choice saves on this device. Connect Google and your other tools when you are ready.'}];
export function GuidedTour({onNavigate,onClose}:{onNavigate:(p:string)=>void;onClose:()=>void}){const [step,setStep]=useState(0);const ref=useRef<HTMLDivElement>(null);useDialog(ref,onClose);useEffect(()=>{onNavigate(steps[step].page)},[step]);const finish=()=>{try{localStorage.setItem('kp-tour-complete','true')}catch{}onNavigate('Overview');onClose()};return <div className="xp-overlay xp-tour-overlay"><div className="xp-backdrop"/><div className="xp-tour" role="dialog" aria-modal="true" aria-labelledby="xp-tour-title" ref={ref}><div className="xp-tour-top"><span>QUICK START · {step+1} OF {steps.length}</span><button aria-label="Close tutorial" onClick={onClose}>×</button></div><div className="xp-tour-progress">{steps.map((s,i)=><i key={s.page} className={i<=step?'done':''}/>)}</div><h2 id="xp-tour-title">{steps[step].title}</h2><p>{steps[step].text}</p><div className="xp-tour-actions"><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button className="xp-primary" onClick={()=>step===steps.length-1?finish():setStep(step+1)}>{step===steps.length-1?'Ready to go':'Next →'}</button></div><small>This tour explains the screens. It won't create or send anything.</small></div></div>}

const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const eventDay=(e:any)=>/^\d{4}-\d{2}-\d{2}$/.test(e.start||'')?e.start:dateKey(new Date(e.start));
export function CalendarGrid({onNavigate}:{onNavigate:(p:string)=>void}){
 const [events,setEvents]=useState<any[]>([]),[status,setStatus]=useState('LOADING'),[selected,setSelected]=useState(dateKey(new Date())),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const load=()=>{setStatus('LOADING');api.calendarUpcoming().then(x=>{setEvents(x.events||[]);setStatus(x.status||'CONNECTED')}).catch(()=>setStatus('UNAVAILABLE'))};useEffect(load,[]);
 const cells=Array.from({length:Math.ceil((month.getDay()+new Date(month.getFullYear(),month.getMonth()+1,0).getDate())/7)*7},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i-month.getDay()+1));
 const shown=events.filter(e=>eventDay(e)===selected);const change=(n:number)=>{const d=new Date(month.getFullYear(),month.getMonth()+n,1);setMonth(d);setSelected(dateKey(d))};
 return <section className="card xp-calendar"><div className="xp-section-head"><div><p className="xp-eyebrow">YOUR TIME</p><h3>Calendar</h3></div><button aria-label="Refresh calendar" onClick={load}>↻</button></div><div className="xp-month-head"><button aria-label="Previous month" onClick={()=>change(-1)}>‹</button><b>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</b><button aria-label="Next month" onClick={()=>change(1)}>›</button></div><div className="xp-calendar-grid"><div className="xp-weekdays">{['S','M','T','W','T','F','S'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="xp-days">{cells.map(d=>{const key=dateKey(d),count=events.filter(e=>eventDay(e)===key).length;return <button key={key} className={`${d.getMonth()!==month.getMonth()?'outside':''} ${key===selected?'selected':''} ${key===dateKey(new Date())?'today':''}`} aria-pressed={key===selected} aria-label={`${d.toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}${count?`, ${count} events`:''}`} onClick={()=>setSelected(key)}><span>{d.getDate()}</span><i className={count?'has-events':''}/></button>})}</div></div><div className="xp-day-agenda"><div className="xp-section-head"><b>{new Date(selected+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</b><button onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelected(dateKey(now))}}>Today</button></div>{status==='LOADING'?<p role="status">Loading your calendar…</p>:status!=='CONNECTED'?<div className="xp-calendar-empty"><p>{status==='DISABLED'?'Connect your calendar to see upcoming meetings.':'Calendar could not load. Try refreshing or check your Google connection.'}</p><button onClick={()=>onNavigate('Settings')}>Calendar settings →</button></div>:shown.length?shown.map(e=><div className="xp-calendar-event" key={e.calendar_id+e.id}><span>{/^\d{4}-\d{2}-\d{2}$/.test(e.start)?'All day':new Date(e.start).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</span><div><b>{e.title||'Untitled event'}</b>{e.location&&<small>{e.location}</small>}{e.html_link&&<a href={e.html_link} target="_blank" rel="noreferrer">Open event ↗</a>}</div></div>):<p className="xp-calendar-empty">No upcoming events returned for this day.</p>}</div><small className="xp-calendar-note">Shows upcoming events from Google. Past events and a full month may not be included.</small><button className="xp-text-action" onClick={()=>onNavigate('Follow-Up / Schedule Hub')}>Manage follow-ups & consultations →</button></section>
}

export function Dashboard({campaign,onNavigate,onTour}:{campaign:string;onNavigate:(p:string)=>void;onTour:()=>void}){
 const [metrics,setMetrics]=useState<any>(null),[queue,setQueue]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setMetrics(null);setQueue(null);setError('');api.metrics(campaign).then(x=>{if(active)setMetrics(x)}).catch(()=>{if(active)setError('Progress is unavailable right now. Your shortcuts still work.')});api.queue(campaign).then(x=>{if(active)setQueue(x)}).catch(()=>{if(active)setError('The queue could not load. Try reopening Overview.')});return()=>{active=false}},[campaign]);
 const actions=[{page:'Up Next',icon:'sell',name:'Start selling',hint:'One prospect at a time'},{page:'Add Prospect',icon:'plus',name:'Add prospect',hint:'Someone you just met'},{page:'Lead Generator',icon:'search',name:'Find prospects',hint:'Build your pipeline'},{page:'Follow-Up / Schedule Hub',icon:'calendar',name:'Follow-ups',hint:'Plan your next move'},{page:'Prospects',icon:'people',name:'All prospects',hint:'Your saved connections'},{page:'Daily Queue',icon:'queue',name:'Daily queue',hint:'Review today’s list'}];
 const first=queue?.daily_queue?.find((p:any)=>!['BOOKED','NOT_INTERESTED','FOLLOW_UP'].includes(p.sales_status));
 return <div className="xp-dashboard"><section className="xp-welcome"><p className="xp-eyebrow">A LITTLE MOMENTUM, EVERY DAY</p><h2>Make your next connection.</h2><p>Find someone. Start a conversation. Save the next step.</p><button onClick={onTour}>{stored('kp-tour-complete','')?'Replay the quick tour':'New here? Take the quick tour'} →</button></section><div className="xp-actions">{actions.map(a=><button className={a.page==='Up Next'?'xp-featured':''} key={a.page} onClick={()=>onNavigate(a.page)}><span className="xp-action-icon"><Icon name={a.icon}/></span><b>{a.name}</b><small>{a.hint}</small></button>)}</div><div className="xp-utility"><button onClick={()=>onNavigate('Campaigns')}>Campaigns</button><button onClick={()=>onNavigate('Settings')}>Appearance & connections</button><button onClick={onTour}>Quick tour</button></div>{error&&<p className="notice" role="status">{error}</p>}<section className="xp-progress" aria-label="Sales progress">{[['In queue',metrics?.queue],['Consultations',metrics?.consultations_set],['Booked',metrics?.booked],['Revenue',metrics?`$${Number(metrics.booked_revenue||0).toLocaleString()}`:null]].map(([name,value])=><div key={name}><strong>{value??'—'}</strong><span>{name}</span></div>)}</section><div className="xp-overview-grid"><section className="card xp-next-card"><p className="xp-eyebrow">ONE STEP AT A TIME</p><h3>{first?'Ready when you are.':queue?'Your pipeline starts here.':'Loading your queue…'}</h3><p>{first?first.business_name||first.name||first.business:queue?'Find prospects for your campaign, or add someone you’ve met. Then review your daily queue.':'We’re getting your next prospect ready.'}</p><button className="xp-primary" onClick={()=>onNavigate(first?'Up Next':'Lead Generator')}>{first?'Open next prospect →':'Find my first prospects →'}</button>{queue&&!first&&<button className="xp-text-action" onClick={()=>onNavigate('Add Prospect')}>Already have someone in mind? Add them →</button>}</section><CalendarGrid onNavigate={onNavigate}/></div></div>
}
