import React,{useRef,useState} from 'react';
import {api} from './api';
import {useSurfaceDialog} from './useSurfaceDialog';
export const campaignRows=(data:any):any[]=>Array.isArray(data)?data:data.campaigns||[];
export async function ensureSearchCampaign(selected:string,criteria:any){const row=await api.campaignResolveTarget({industry:criteria.industry.trim(),city:criteria.city.trim(),state:criteria.state,preferred_campaign:selected||undefined});return row.campaign_id;}
export function CampaignPicker({campaign,campaigns,onCampaign,onCreated}:{campaign?:string;campaigns:any[];onCampaign:(id:string)=>void;onCreated?:(id:string,rows:any[])=>void}){
 const [open,setOpen]=useState(false),[form,setForm]=useState({name:'',category:'',city:'',state:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const id=useRef(''),lock=useRef(false),edited=useRef(false);const close=()=>{if(!lock.current)setOpen(false)};const dialog=useSurfaceDialog(open,close);
 const begin=()=>{id.current=`search_${crypto.randomUUID()}`;edited.current=false;const current=campaigns.find(c=>c.campaign_id===campaign);setForm({name:'',category:current?.category||'',city:current?.city||'',state:current?.state||''});setError('');setOpen(true);Promise.all([api.discoveryTarget(),campaign?api.discoverySearches(campaign):Promise.resolve([])]).then(([target,searches])=>{if(edited.current)return;const c=searches[0]?.criteria||target.criteria||{};setForm(f=>({...f,category:c.industry||f.category,city:c.city||f.city,state:c.state||f.state}))}).catch(()=>{});};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{let rows=campaignRows(await api.campaigns());if(!rows.some(c=>c.campaign_id===id.current))await api.campaignCreate({...form,name:form.name.trim(),category:form.category.trim(),city:form.city.trim(),campaign_id:id.current,daily_queue_limit:50,status:'ACTIVE'});rows=campaignRows(await api.campaigns());if(!rows.some(c=>c.campaign_id===id.current))throw Error('The new campaign could not refresh.');onCreated?.(id.current,rows);onCampaign(id.current);setOpen(false)}catch(e:any){setError(`Could not finish creating this campaign. Your fields are kept. Try again. ${e.message||''}`)}finally{lock.current=false;setBusy(false)}};
 return <><label>Campaign<select aria-label="Current campaign" value={campaigns.some(c=>c.campaign_id===campaign)?campaign:''} onChange={e=>{if(e.target.value==='__new__'){begin();e.target.value=campaign||''}else onCampaign(e.target.value)}}>{!campaigns.length&&<option value="">Your customer search</option>}{campaigns.map(c=><option key={c.campaign_id} value={c.campaign_id}>{c.name||c.campaign_id}</option>)}<option value="__new__">＋ New campaign</option></select></label>{open&&<div className="xp-overlay"><div className="xp-backdrop" onClick={close}/><div ref={dialog} className="kp-campaign-dialog" role="dialog" aria-modal="true" aria-labelledby="new-campaign-title"><h2 id="new-campaign-title">New campaign</h2><p>A campaign keeps a customer search and its saved businesses together.</p><form onSubmit={submit}>{[['name','Campaign name'],['category','Business type'],['city','City'],['state','State (e.g. GA)']].map(([key,label])=><label key={key}>{label}<input required disabled={busy} value={form[key as keyof typeof form]} maxLength={key==='state'?2:120} pattern={key==='state'?'[A-Z]{2}':undefined} onChange={e=>{edited.current=true;setForm(f=>({...f,[key]:key==='state'?e.target.value.toUpperCase():e.target.value}))}}/></label>)}{error&&<p role="alert">{error}</p>}<div className="dw-actions"><button className="dw-primary" disabled={busy}>{busy?'Creating…':'Create campaign'}</button><button type="button" disabled={busy} onClick={close}>Cancel</button></div></form></div></div>}</>;
}
