import React,{useEffect,useMemo,useState} from 'react';
import {api,authApi} from './api';

const cash=(value:any)=>`$${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const words=(value:any)=>String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const readQualification=(lead:any)=>{try{return lead.qualification||JSON.parse(lead.qualification_json||'{}')}catch{return {}}};
const Empty=({title,body,action,onAction}:{title:string;body:string;action?:string;onAction?:()=>void})=><section className="kx-empty"><span>✦</span><h2>{title}</h2><p>{body}</p>{action&&<button className="kx-button" onClick={onAction}>{action}</button>}</section>;
const Meter=({value,label}:{value:number;label:string})=><div className="kx-meter" aria-label={label}><i style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>;

export function CoreHome({campaign,onNavigate}:{campaign:string;onNavigate:(page:string)=>void}){
 const [center,setCenter]=useState<any>(null),[momentum,setMomentum]=useState<any>(null),[user,setUser]=useState<any>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{setFailed(false);Promise.all([api.commandCenter(campaign),api.momentum(),authApi.me()]).then(([a,b,c])=>{setCenter(a);setMomentum(b);setUser(c)}).catch(()=>setFailed(true))},[campaign]);
 if(failed)return <Empty title="Your sales day could not load." body="Give it another try. Your leads and progress are still safe." action="Try again" onAction={()=>location.reload()}/>;
 if(!center||!momentum)return <section className="kx-loading"><span/><h2>Finding today’s best moves…</h2><p>Ranking fit, timing, and follow-ups.</p></section>;
 const prospects=(center.prospects_needing_outreach||[]).map((x:any)=>({...x,kind:'LEAD'})),followups=(center.followups_due||[]).map((x:any)=>({...x,kind:'FOLLOW_UP'}));
 const moves=[...prospects,...followups].sort((a,b)=>Number(b.icp_score??b.score??0)-Number(a.icp_score??a.score??0));
 const mission=momentum.mission||{},weekly=momentum.weekly_goal||{},target=Number(mission.contacts_target||8),done=Number(mission.contacts||0),first=String(user?.name||user?.username||'').trim().split(/\s+/)[0];
 const hour=new Date().getHours(),hello=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening';
 return <div className="kx-home">
  <section className="kx-launch">
   <div className="kx-launch-copy"><p className="kx-kicker">YOUR SALES DAY</p><h1>{hello}{first?`, ${first}`:''}.</h1><p className="kx-launch-line"><b>{moves.length}</b> moves are worth your time today.</p><button className="kx-start" onClick={()=>onNavigate('Up Next')}><span>Start selling</span><b>→</b></button></div>
   <div className="kx-mission"><div className="kx-mission-ring" style={{'--progress':`${Math.min(100,target?done/target*100:0)}%`} as React.CSSProperties}><strong>{Math.max(0,target-done)}</strong><small>moves left</small></div><div><span>DAILY MISSION</span><h2>{mission.complete?'Mission complete':'Start the next conversations'}</h2><p>{done} of {target} qualified leads contacted</p><Meter value={target?done/target*100:0} label={`${done} of ${target} contacts`}/><small>{mission.complete?'You did the work. Let the pipeline cook.':`Finish it for +${mission.reward||25} Momentum`}</small></div></div>
  </section>
  <section className="kx-opportunities"><header><div><p className="kx-kicker">TODAY’S BEST MOVES</p><h2>Who are we going after?</h2></div><button onClick={()=>onNavigate('Prospects')}>All leads →</button></header>
   {moves.length?<div className="kx-opportunity-rail">{moves.slice(0,3).map((lead:any)=>{const q=readQualification(lead),company=lead.company||lead.business_name||lead.name||'Opportunity',score=lead.icp_score??lead.score;return <article key={`${lead.kind}-${lead.id||lead.prospect_id}`}><div className="kx-opportunity-top"><span>{lead.kind==='FOLLOW_UP'?'FOLLOW UP':`${score??'—'} MATCH`}</span><b>{words(lead.icp_priority||lead.priority||'Ready')}</b></div><h3>{company}</h3><p>{lead.kind==='FOLLOW_UP'?(lead.next_action?.action||'Keep the conversation moving.'):(q.matches?.[0]||q.signals?.[0]||lead.route_reason||'A strong match worth reviewing.')}</p><button onClick={()=>onNavigate(lead.kind==='FOLLOW_UP'?'Calendar':'Up Next')}>{lead.kind==='FOLLOW_UP'?'Handle follow-up':'Contact now'} <span>→</span></button></article>})}</div>:<Empty title="You’re caught up." body="Find a few strong prospects when you are ready to build the next conversation." action="Find leads" onAction={()=>onNavigate('Lead Generator')}/>} 
  </section>
  <section className="kx-home-footer"><div><span>THIS WEEK</span><strong>{weekly.meaningful_moves||0}<small> / {weekly.target||40} moves</small></strong><Meter value={Number(weekly.meaningful_moves||0)/Math.max(1,Number(weekly.target||40))*100} label="Weekly goal progress"/><p>{weekly.remaining??40} left · {momentum.selling_rhythm?.active_days||0} active days</p></div><div><span>PIPELINE IN MOTION</span><strong>{cash(center.pipeline_value)}</strong><p>{center.active_leads||0} active · {center.upcoming_consultations?.length||0} booked</p><button onClick={()=>onNavigate('Leads')}>View pipeline →</button></div><button className="kx-level" onClick={()=>onNavigate('Momentum')}><span>{momentum.level?.name||'Starter'}</span><b>{momentum.total||0}</b><small>Momentum</small></button></section>
 </div>
}

export function CoreLeads({campaign,onNavigate,onOpenContact}:{campaign:string;onNavigate:(page:string)=>void;onOpenContact:(lead:any)=>void}){
 const [rows,setRows]=useState<any[]|null>(null),[query,setQuery]=useState(''),[priority,setPriority]=useState('ALL'),[status,setStatus]=useState('ALL'),[filters,setFilters]=useState(false),[selection,setSelection]=useState(false),[selected,setSelected]=useState<number[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>api.lifecycleContacts('PROSPECT',campaign).then(setRows).catch(()=>setRows([]));useEffect(()=>{void load();setSelected([])},[campaign]);
 const statuses=Array.from(new Set((rows||[]).map(x=>x.sales_status||'NOT_CONTACTED')));
 const visible=useMemo(()=>(rows||[]).filter(lead=>{const hay=[lead.company,lead.name,lead.category,lead.city,lead.state].filter(Boolean).join(' ').toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(priority==='ALL'||lead.icp_priority===priority)&&(status==='ALL'||(lead.sales_status||'NOT_CONTACTED')===status)}).sort((a,b)=>Number(b.icp_score??b.score??0)-Number(a.icp_score??a.score??0)),[rows,query,priority,status]);
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const rescore=async()=>{setBusy(true);setMessage('');let complete=0;for(const id of selected){try{await api.rescoreLead(id,false);complete++}catch{}}setMessage(`${complete} lead${complete===1?'':'s'} rescored with your current ICP.`);setSelected([]);setSelection(false);await load();setBusy(false)};
 return <div className="kx-browser"><header className="kx-browser-head"><div><p className="kx-kicker">OPPORTUNITY BROWSER</p><h1>Find the right lead.</h1><p>Search quickly. Open the reasoning only when you need it.</p></div><button className="kx-button" onClick={()=>onNavigate('Lead Generator')}>Find leads</button></header>
  <div className="kx-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Search company, industry, or location"/><button onClick={()=>setFilters(true)}>Filters{priority!=='ALL'||status!=='ALL'?' •':''}</button></div>
  <div className="kx-browser-actions"><span>{visible.length} opportunities</span><div>{selection?<><button onClick={()=>{setSelection(false);setSelected([])}}>Cancel</button><button disabled={!selected.length||busy} onClick={rescore}>{busy?'Rescoring…':`Rescore ${selected.length}`}</button></>:<><button onClick={()=>setSelection(true)}>Select</button><button onClick={()=>onNavigate('Add Prospect')}>+ Add lead</button></>}</div></div>
  {message&&<p className="kx-feedback">{message}</p>}
  {rows===null?<section className="kx-loading"><span/><h2>Ranking your opportunities…</h2></section>:visible.length?<div className="kx-lead-list">{visible.map(lead=>{const q=readQualification(lead),checked=selected.includes(lead.id);return <article className={checked?'is-selected':''} key={lead.id}>{selection&&<button className="kx-check" aria-pressed={checked} aria-label={`Select ${lead.company||lead.name}`} onClick={()=>toggle(lead.id)}>{checked?'✓':''}</button>}<button className="kx-lead-open" onClick={()=>selection?toggle(lead.id):onOpenContact({...lead,prospect_id:lead.id})}><div className="kx-lead-score"><strong>{lead.icp_score??lead.score??'—'}</strong><small>MATCH</small></div><div className="kx-lead-copy"><div><span>{words(lead.icp_priority||'Unscored')}</span>{lead.last_scored_at&&<small>{new Date(lead.last_scored_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small>}</div><h2>{lead.company||lead.name}</h2><p>{[lead.category,[lead.city,lead.state].filter(Boolean).join(', ')].filter(Boolean).join(' · ')}</p><b>{q.matches?.[0]||q.signals?.[0]||'Open to see why this lead matches.'}</b></div><span className="kx-arrow">→</span></button></article>})}</div>:<Empty title="No strong matches here." body="Clear a filter or find new leads that fit your ICP." action="Find leads" onAction={()=>onNavigate('Lead Generator')}/>} 
  {filters&&<div className="kx-sheet-wrap"><button className="kx-sheet-backdrop" onClick={()=>setFilters(false)} aria-label="Close filters"/><section className="kx-sheet" role="dialog" aria-modal="true" aria-labelledby="filter-title"><i/><header><div><p className="kx-kicker">REFINE THE LIST</p><h2 id="filter-title">Lead filters</h2></div><button onClick={()=>setFilters(false)}>×</button></header><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="ALL">All priorities</option>{['HIGH_PRIORITY','GOOD_FIT','REVIEW','LOW_PRIORITY','UNSCORED'].map(x=><option value={x} key={x}>{words(x)}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{statuses.map(x=><option value={x} key={x}>{words(x)}</option>)}</select></label><div><button onClick={()=>{setPriority('ALL');setStatus('ALL')}}>Clear</button><button className="kx-button" onClick={()=>setFilters(false)}>Show {visible.length} leads</button></div></section></div>}
 </div>
}

const stages=['NEW_LEAD','CONSULTATION','PROPOSAL','DECISION','WON','LOST'];
export function CorePipeline({campaign,onOpenContact}:{campaign:string;onOpenContact:(lead:any)=>void}){
 const [deals,setDeals]=useState<any[]|null>(null),[stage,setStage]=useState('NEW_LEAD'),[selected,setSelected]=useState<any>(null);useEffect(()=>{api.deals(campaign).then(setDeals).catch(()=>setDeals([]))},[campaign]);
 if(deals===null)return <section className="kx-loading"><span/><h2>Building your pipeline view…</h2></section>;
 const active=deals.filter(x=>x.status==='ACTIVE'),potential=active.reduce((n,x)=>n+Number(x.deal_value||0),0),shown=deals.filter(x=>x.stage===stage);
 return <div className="kx-pipeline"><header><div><p className="kx-kicker">PIPELINE IN MOTION</p><h1>Move the money forward.</h1><p>Potential value is opportunity, not guaranteed revenue.</p></div><div className="kx-pipeline-total"><span>POTENTIAL</span><strong>{cash(potential)}</strong><small>{active.length} active opportunities</small></div></header>
  <nav className="kx-stage-nav" aria-label="Pipeline stages">{stages.map(x=><button className={stage===x?'active':''} onClick={()=>setStage(x)} key={x}><span>{words(x)}</span><b>{deals.filter(d=>d.stage===x).length}</b></button>)}</nav>
  <section className="kx-stage"><header><div><p className="kx-kicker">CURRENT STAGE</p><h2>{words(stage)}</h2></div><strong>{cash(shown.reduce((n,x)=>n+Number(x.deal_value||0),0))}</strong></header>{shown.length?<div className="kx-deals">{shown.map(deal=><button key={deal.id} onClick={()=>setSelected(deal)}><div><span>{deal.next_action_at?new Date(deal.next_action_at).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'NEXT STEP NEEDED'}</span><h3>{deal.contact?.company||deal.contact?.name||'Opportunity'}</h3><p>{deal.name}</p></div><strong>{cash(deal.deal_value)}</strong><div className="kx-next"><small>NEXT MOVE</small><b>{deal.next_action||'Set the next action'}</b></div><i>→</i></button>)}</div>:<Empty title={`No ${words(stage)} deals.`} body="Opportunities will appear here as conversations move forward."/>}</section>
  {selected&&<div className="kx-sheet-wrap"><button className="kx-sheet-backdrop" onClick={()=>setSelected(null)} aria-label="Close deal"/><section className="kx-sheet" role="dialog" aria-modal="true"><i/><header><div><p className="kx-kicker">OPPORTUNITY</p><h2>{selected.contact?.company||selected.contact?.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><h3>{selected.name}</h3><p>{cash(selected.deal_value)} · {words(selected.stage)}</p><div className="kx-sheet-callout"><small>NEXT MOVE</small><b>{selected.next_action||'Set a clear next action'}</b><span>{selected.next_action_at?new Date(selected.next_action_at).toLocaleString():'No follow-up scheduled'}</span></div><button className="kx-button" onClick={()=>onOpenContact({...selected.contact,prospect_id:selected.contact?.id})}>Open full opportunity</button></section></div>}
 </div>
}

export function CoreMomentum(){
 const [data,setData]=useState<any>(null);useEffect(()=>{api.momentum().then(setData).catch(()=>setData({total:0,level:{name:'Starter'},mission:{},weekly_goal:{},selling_rhythm:{}}))},[]);if(!data)return <section className="kx-loading"><span/><h2>Gathering your progress…</h2></section>;
 const level=data.level||{},mission=data.mission||{},weekly=data.weekly_goal||{},progress=level.next_at?((data.total-level.floor)/(level.next_at-level.floor))*100:100;
 return <div className="kx-momentum"><section className="kx-level-hero"><div><p className="kx-kicker">KP MOMENTUM</p><h1>{level.name}</h1><p>Professional progress built from real selling work.</p></div><div className="kx-orbit" style={{'--progress':`${Math.min(100,progress)}%`} as React.CSSProperties}><strong>{data.total||0}</strong><small>Momentum</small></div><footer><Meter value={progress} label="Level progress"/><span>{level.next_name?`${level.remaining} until ${level.next_name}`:'Top level reached'}</span></footer></section>
  <div className="kx-momentum-flow"><section className="kx-mission-feature"><div><p className="kx-kicker">TODAY’S MISSION</p><h2>{mission.complete?'Mission complete':'Start the next conversations'}</h2><p>{mission.moves_remaining??0} meaningful moves left.</p><Meter value={Number(mission.contacts||0)/Math.max(1,Number(mission.contacts_target||8))*100} label="Daily mission progress"/></div><div><strong>{mission.contacts||0}<small> / {mission.contacts_target||8}</small></strong><span>qualified contacts</span><b>+{mission.reward||25}</b></div></section>
   <section className="kx-week"><header><span>THIS WEEK</span><b>{weekly.meaningful_moves||0} / {weekly.target||40}</b></header><Meter value={Number(weekly.meaningful_moves||0)/Math.max(1,Number(weekly.target||40))*100} label="Weekly progress"/><div>{[['Contacts',weekly.contacts],['Replies',weekly.replies],['Meetings',weekly.meetings],['Proposals',weekly.proposals]].map(([x,v])=><span key={String(x)}><b>{v||0}</b><small>{x}</small></span>)}</div><p>{data.selling_rhythm?.active_days||0} active selling days · Best week {data.selling_rhythm?.best_week||0}</p></section>
   <section className="kx-activity"><header><div><span>RECENT MOMENTUM</span><h2>Work that counted.</h2></div></header>{data.recent?.length?data.recent.slice(0,6).map((x:any,i:number)=><div key={`${x.created_at}-${i}`}><span><b>{words(x.event_type)}</b><small>{new Date(x.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></span><strong>+{x.points}</strong></div>):<p>Your meaningful selling activity will appear here.</p>}</section>
   <section className="kx-milestones"><span>PERSONAL MILESTONES</span><div>{data.personal_records?.length?data.personal_records.slice(0,4).map((x:any)=><article key={x.name}><strong>{x.currency?cash(x.value):x.value}</strong><b>{x.name}</b><small>{x.detail}</small></article>):<p>Your first reply, meeting, proposal, and win will show up here.</p>}</div></section>
   {data.next_unlock&&<section className="kx-unlock"><span>UP NEXT</span><h2>{data.next_unlock.name}</h2><p>{data.next_unlock.description}</p><b>{data.next_unlock.remaining} Momentum to unlock</b></section>}
  </div>
 </div>
}

export function CoreMore({onNavigate}:{onNavigate:(page:string)=>void}){
 const groups=[['SELLING TOOLS',[['ICP Profile','Define your best customer'],['Campaigns','Markets and lead searches'],['Calendar','Follow-ups and meetings']]],['BUSINESS',[['Customers','Relationships and repeat work'],['Sales & Revenue','Closed and collected value'],['Momentum','Progress and milestones']]],['SYSTEM',[['Runs','Lead generation history'],['Settings','Appearance and connections']]]];
 return <div className="kx-more"><header><p className="kx-kicker">MORE</p><h1>Everything else, when you need it.</h1><p>Your daily selling flow stays focused.</p></header>{groups.map(([name,items]:any)=><section key={name}><span>{name}</span>{items.map(([page,hint]:string[])=><button key={page} onClick={()=>onNavigate(page)}><div><b>{page}</b><small>{hint}</small></div><strong>→</strong></button>)}</section>)}</div>
}
