import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {api} from './api';
import {GuidedReview} from './GuidedReview';
import {useSurfaceDialog} from './useSurfaceDialog';

const decisionLabels:any={QUALIFIED:'Looks like a fit',NEEDS_RESEARCH:'Not sure',DISQUALIFIED:'Not a fit',UNREVIEWED:'Not reviewed'};
const fitLabel=(x:string)=>x==='Matches stated criteria'?'Matches what you asked for':x==='Outside criteria'?"Some details don’t match":'Some details are missing';
const words=(x:any)=>String(x||'').replace(/_/g,' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
const emptyCriteria={industry:'',city:'',state:'',limit:10,min_rating:0,min_reviews:0,website_required:false};
const safeLink=(value:any)=>{try{const raw=String(value||'');if(!raw)return undefined;const url=new URL(/^https?:/i.test(raw)?raw:`https://${raw}`);return ['http:','https:'].includes(url.protocol)&&!url.username?url.href:undefined}catch{return undefined}};
const mainScroller=()=>document.querySelector('.shell > main') as HTMLElement|null;

export function DiscoveryWorkspace({campaign,home=false,onNavigate,onCampaignReady,onOpenSaved,onContext,initialBusinessId}:{campaign:string;home?:boolean;onNavigate:(page:string)=>void;onCampaignReady?:(id:string)=>void;onOpenSaved:(lead:any)=>void;onContext?:(ids:number[])=>void;initialBusinessId?:number}){
 const [target,setTarget]=useState<any>(null),[criteria,setCriteria]=useState<any>(emptyCriteria),[profile,setProfile]=useState<any>({}),[searches,setSearches]=useState<any[]>([]),[result,setResult]=useState<any>(null),[saved,setSaved]=useState<any[]>([]),[tab,setTab]=useState('results'),[step,setStep]=useState(0),[help,setHelp]=useState(false),[editing,setEditing]=useState(false),[guided,setGuided]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[query,setQuery]=useState(''),[decision,setDecision]=useState('ALL'),[contact,setContact]=useState('ALL'),[fit,setFit]=useState('WITHIN'),[sort,setSort]=useState('fit'),[selected,setSelected]=useState<number[]>([]),[opened,setOpened]=useState<any>(null),[allowance,setAllowance]=useState<any>(null);
 const setupKey=useRef(''),storageKey=useRef(''),restoreScroll=useRef<number|null>(null),scrollerPosition=useRef(0),activeCampaign=useRef(campaign),alive=useRef(true);
 const loadHistory=(c=activeCampaign.current)=>api.discoverySearches(c).then(setSearches);
 const loadSaved=(c=activeCampaign.current)=>api.discoverySaved(c).then(setSaved);
 const loadResult=(id:string)=>api.discoveryResults(id).then(x=>{setResult(x);return x});
 useEffect(()=>{let cancelled=false;alive.current=true;setReady(false);setError('');setResult(null);setSaved([]);setSearches([]);activeCampaign.current=campaign;
  Promise.all([api.discoveryTarget(),api.discoverySettings().catch((e:any)=>({available:false,message:e.message==='API_401'?'Sign in to the hosted app to use built-in searches.':'Search access could not load. Refresh or ask your workspace owner for help.'})),api.campaigns()]).then(async([t,a,all]:any[])=>{
   if(cancelled)return;setTarget(t);setProfile(t.profile||{});setAllowance(a);setStep(t.profile?.offer?3:0);
   const defaults=t.criteria?.industry?t.criteria:{...emptyCriteria,industry:(t.profile?.business_types||t.profile?.target_industries||[])[0]||'',city:(t.profile?.geography?.[0]||'').split(',')[0],state:(t.profile?.geography?.[0]||'').split(',')[1]?.trim().toUpperCase()||''};setCriteria({...emptyCriteria,...defaults});
   setupKey.current=`kp-discovery-setup:${t.user_id}`;
   try{const draft=JSON.parse(sessionStorage.getItem(setupKey.current)||'{}');if(draft.version===t.version){setProfile({...t.profile,offer:draft.offer||t.profile?.offer||''});setCriteria({...emptyCriteria,...defaults,...draft.criteria});if(Number.isInteger(draft.step)&&draft.step>=0&&draft.step<=3)setStep(draft.step)}}catch{}
   const rows=Array.isArray(all)?all:all.campaigns||[];if(!rows.length){setReady(true);return}
   const current=rows.find((c:any)=>c.campaign_id===campaign)?.campaign_id||rows[0].campaign_id;activeCampaign.current=current;
   storageKey.current=`kp-discovery:${t.user_id}:${current}`;
   let remembered:any={};try{remembered=JSON.parse(sessionStorage.getItem(storageKey.current)||'{}')}catch{}
   setQuery(remembered.query||'');setDecision(remembered.decision||'ALL');setContact(remembered.contact||'ALL');setFit(remembered.fit||'WITHIN');setSort(remembered.sort||'fit');setTab(remembered.tab||'results');setGuided(remembered.guided!==false);restoreScroll.current=remembered.scroll??0;
   const [history,leads]=await Promise.all([api.discoverySearches(current),api.discoverySaved(current)]);if(cancelled)return;setSearches(history);setSaved(leads);
   const id=history.some((x:any)=>x.id===remembered.search)?remembered.search:history[0]?.id;
   if(id){const data=await api.discoveryResults(id);if(!cancelled)setResult(data)}
   if(!cancelled)setReady(true);
  }).catch((e:any)=>{if(!cancelled){setError(e.message||'Discovery could not load.');setReady(true)}});
  return()=>{cancelled=true;alive.current=false};
 },[campaign]);
 useEffect(()=>{
  if(!ready||!storageKey.current)return;
  const persist=()=>{try{sessionStorage.setItem(storageKey.current,JSON.stringify({query,decision,contact,fit,sort,tab,guided,search:result?.id,scroll:mainScroller()?.scrollTop||0}))}catch{}};
  const scroller=mainScroller();scroller?.addEventListener('scroll',persist,{passive:true});persist();return()=>{scroller?.removeEventListener('scroll',persist);persist()};
 },[ready,query,decision,contact,fit,sort,tab,guided,result?.id]);
 useEffect(()=>{if(!ready||!setupKey.current||result&&!editing)return;try{sessionStorage.setItem(setupKey.current,JSON.stringify({version:target?.version,offer:profile.offer,criteria,step}))}catch{}},[ready,profile.offer,criteria,step,target?.version,result?.id,editing]);
 useEffect(()=>{if(ready&&result&&restoreScroll.current!==null){const y=restoreScroll.current;restoreScroll.current=null;requestAnimationFrame(()=>mainScroller()?.scrollTo({top:y}))}},[ready,result]);
 useEffect(()=>{if(result?.status!=='SEARCHING')return;const id=result.id;const timer=setInterval(()=>api.discoveryResults(id).then(x=>{if(alive.current)setResult(x)}).catch(()=>setError('Search progress could not refresh. Resume it from recent searches.')),2500);return()=>clearInterval(timer)},[result?.id,result?.status]);
 useEffect(()=>{if(ready&&initialBusinessId&&!opened){api.discoveryDetail(initialBusinessId).then(setOpened).catch((e:any)=>setError(e.message))}},[ready,initialBusinessId]);
 const reset=()=>{setQuery('');setDecision('ALL');setContact('ALL');setFit('WITHIN');setSort('fit');setSelected([])};
 const run=async()=>{
  setBusy(true);setError('');setMessage('');reset();setGuided(true);
  let c=activeCampaign.current;
  try{
   const all=await api.campaigns();const rows=Array.isArray(all)?all:all.campaigns||[];
   if(!rows.length){c=`discovery_${crypto.randomUUID().slice(0,8)}`;await api.campaignCreate({campaign_id:c,name:'Potential customers',city:criteria.city,state:criteria.state,category:criteria.industry,daily_queue_limit:50,status:'ACTIVE'});activeCampaign.current=c}
   await api.discoverySaveTarget(criteria);
   const updatedProfile=await api.saveIcpProfile({profile:{...profile,business_types:[criteria.industry],target_industries:[criteria.industry],geography:[`${criteria.city}, ${criteria.state}`]},weights:target?.weights,completed:true});setProfile(updatedProfile.profile);setTarget((current:any)=>({...current,...updatedProfile}));try{sessionStorage.removeItem(setupKey.current)}catch{}
   const id=crypto.randomUUID();setResult({id,criteria:{...criteria},status:'SEARCHING',businesses:[]});setTab('results');setEditing(false);
   const data=await api.discoveryRun({id,campaign:c,criteria});if(alive.current)setResult(data);await loadHistory(c);await loadSaved(c);setAllowance(await api.discoverySettings());
   if(c!==campaign)onCampaignReady?.(c);
  }catch(e:any){setError(e.message||'Search failed.');try{await loadHistory(c)}catch{}setResult((r:any)=>r?({...r,status:'FAILED',error:e.message}):r)}finally{setBusy(false)}
 };
 const open=async(row:any)=>{
  setError('');scrollerPosition.current=mainScroller()?.scrollTop||0;
  try{const data=typeof row.id==='string'?await api.discoveryReviewLegacy(row.prospect_id):await api.discoveryDetail(row.id,tab==='results'?result?.id:undefined);setOpened(data);onContext?.([data.id])}catch(e:any){setError(e.message)}
 };
 const close=()=>{setOpened(null);onContext?.([]);requestAnimationFrame(()=>mainScroller()?.scrollTo({top:scrollerPosition.current}))};
 const openSaved=async(row:any)=>{setError('');try{const records=await api.prospects(activeCampaign.current);const record=records.find(x=>x.id===row.prospect_id);if(!record)throw new Error('This saved record is no longer available. Refresh the list.');onOpenSaved({...record,prospect_id:record.id});close()}catch(e:any){setError(e.message)}};
 const updateRow=(row:any)=>{setOpened((current:any)=>current?.id===row.id?row:current);setResult((r:any)=>r?({...r,businesses:(r.businesses||[]).map((x:any)=>x.id===row.id?row:x)}):r);void loadSaved().catch(()=>setError('Saved potential customers could not refresh. Return to potential customers.'))};
 const saveSelected=async()=>{setBusy(true);setError('');try{const outcomes=await api.discoveryBulkSave(selected);const failures=outcomes.filter((x:any)=>x.error);setMessage(`${outcomes.length-failures.length} businesses saved. ${failures.length} need a decision first or could not save.`);setSelected([]);if(result)await loadResult(result.id);await loadSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const allRows=tab==='saved'?saved:result?.businesses||[];
 const visible=useMemo(()=>allRows.filter((r:any)=>{
  const q=r.assessment||{};return (!query||[r.name,r.category,r.city,r.state].join(' ').toLowerCase().includes(query.toLowerCase()))&&(decision==='ALL'||r.decision===decision)&&(contact==='ALL'||contact==='YES'&&q.contact_paths?.length||contact==='NO'&&!q.contact_paths?.length)&&(fit==='ALL'||q.label!=='Outside criteria');
 }).sort((a:any,b:any)=>sort==='name'?String(a.name).localeCompare(String(b.name)):sort==='recent'?String(b.found_at||'').localeCompare(String(a.found_at||'')):(b.assessment?.matches?.length||0)-(a.assessment?.matches?.length||0)),[allRows,query,decision,contact,fit,sort]);
 const active=[query&&`Text: ${query}`,decision!=='ALL'&&decisionLabels[decision],contact!=='ALL'&&`Contact: ${contact==='YES'?'available':'missing'}`,fit==='WITHIN'&&'Hide confirmed mismatches'].filter(Boolean);
 const valid=criteria.industry.trim()&&criteria.city.trim()&&/^[A-Z]{2}$/.test(criteria.state)&&Number.isInteger(criteria.limit)&&criteria.limit>0&&criteria.limit<=100&&criteria.min_rating>=0&&criteria.min_rating<=5&&Number.isInteger(criteria.min_reviews)&&criteria.min_reviews>=0;
 return <div className="dw-workspace">
  <div className="dw-heading"><p className="eyebrow">KP SALES OS</p><h2>{home?'Find potential customers.':'Your potential customers'}</h2><p>Find businesses that might need what you sell. You decide who looks worth contacting.</p></div>
  {error&&<div className="dw-alert" role="alert">{error}<button onClick={()=>location.reload()}>Reload workspace</button></div>}
  {message&&<p role="status">{message}</p>}
  {!ready&&<p role="status">Loading your discovery workspace…</p>}
  {(!result||editing)&&<section className="dw-target" aria-label="Who you want to sell to">
   <p className="dw-step">Step {step+1} of 4 · {['What you sell','Who could use it','Where to look','Check your search'][step]}</p>
   <div className="dw-skye-guide" aria-label="Skye’s guidance"><strong>✦ Skye</strong><p>{[
    'Let’s find a potential customer together. First, what do you sell? A few words are enough.',
    `Who could use ${profile.offer||'what you sell'}? Choose a business type. If you’re unsure, I can help you pick a starting point.`,
    'Where can you serve customers? Choose a city and state, and I’ll keep the search there.',
    'Does this search look right? You can edit it before we start. Then we’ll look at the businesses one at a time.'
   ][step]}</p></div>
   <progress className="dw-progress" max={4} value={step+1} aria-label={`Setup step ${step+1} of 4`}/>
   {step===0&&<><h3>What do you sell?</h3><p>A few words are enough—for example, website design, cleaning, or photography.</p><label>Your product or service<input value={profile.offer||''} onChange={e=>setProfile({...profile,offer:e.target.value})} placeholder="e.g. Website design"/></label><details><summary>Show examples</summary><div className="dw-actions">{['Website design','Cleaning services','Photography','Bookkeeping'].map(x=><button key={x} onClick={()=>setProfile({...profile,offer:x})}>{x}</button>)}</div></details><button className="dw-primary" disabled={!profile.offer?.trim()} onClick={()=>setStep(1)}>Next: who could use it?</button></>}
   {step===1&&<><h3>Who would you like to sell to?</h3><p>Choose one type of business to explore.</p><button onClick={()=>setHelp(x=>!x)} aria-expanded={help}>Skye, help me figure this out</button>{help&&<div className="dw-help"><strong>✦ Skye</strong><p>Choose a type of business you’d like to explore for {profile.offer||'your product or service'}. These starting ideas don’t tell us who wants to buy.</p><div className="dw-actions">{['Hair salon','Restaurant','Dental clinic','Retail store','Real estate agency'].map(x=><button key={x} onClick={()=>setCriteria({...criteria,industry:x})}>{x}</button>)}</div><p>If you sell photography, restaurants are one place to start. We’ll check each business’s details together before you decide.</p></div>}
    <div className="dw-fields"><label>Type of business<input required value={criteria.industry} onChange={e=>setCriteria({...criteria,industry:e.target.value})} placeholder="e.g. Hair salon"/></label></div>
    <div className="dw-actions"><button onClick={()=>setStep(0)}>Back</button><button className="dw-primary" disabled={!criteria.industry.trim()} onClick={()=>setStep(2)}>Next: where should we look?</button></div></>}
   {step===2&&<><h3>Where should we look?</h3><p>Choose a city and state. Start with somewhere you can serve.</p><div className="dw-fields"><label>City<input required value={criteria.city} onChange={e=>setCriteria({...criteria,city:e.target.value})} placeholder="e.g. Orlando"/></label><label>State (e.g. FL)<input required maxLength={2} pattern="[A-Z]{2}" value={criteria.state} onChange={e=>setCriteria({...criteria,state:e.target.value.toUpperCase()})} placeholder="FL"/></label></div><div className="dw-actions"><button onClick={()=>setStep(1)}>Back</button><button className="dw-primary" disabled={!valid} onClick={()=>setStep(3)}>Next: check my search</button></div></>}
   {step===3&&<><h3>Here’s who we’ll look for</h3><p className="dw-criteria-summary">You sell <strong>{profile.offer||'your product or service'}</strong>. We’ll find <strong>{criteria.industry||'businesses'}</strong> in <strong>{criteria.city||'your city'}, {criteria.state||'your state'}</strong>{criteria.website_required?' with a website':''}{criteria.min_rating?`, rated at least ${criteria.min_rating}`:''}{criteria.min_reviews?`, with at least ${criteria.min_reviews} reviews`:''}.</p><button onClick={()=>setStep(1)}>Edit business type</button><button onClick={()=>setStep(2)}>Edit location</button><button onClick={()=>setStep(0)}>Edit what I sell</button>
    <details><summary>More search options</summary><div className="dw-fields"><label>Businesses to request<input type="number" min={1} max={100} value={criteria.limit} onChange={e=>setCriteria({...criteria,limit:Number(e.target.value)})}/></label><label>Minimum rating<input type="number" min={0} max={5} step={0.1} value={criteria.min_rating} onChange={e=>setCriteria({...criteria,min_rating:Number(e.target.value)})}/></label><label>Minimum reviews<input type="number" min={0} value={criteria.min_reviews} onChange={e=>setCriteria({...criteria,min_reviews:Number(e.target.value)})}/></label><label className="dw-check"><input type="checkbox" checked={criteria.website_required} onChange={e=>setCriteria({...criteria,website_required:e.target.checked})}/>Website required</label></div><p>Ratings and reviews come from available listings. They do not show buying interest.</p><button onClick={()=>onNavigate('ICP Profile')}>More about who I want to sell to</button></details>
    <div className="dw-actions"><button className="dw-primary" disabled={!ready||busy||!valid||!allowance?.available||criteria.limit>allowance.max_per_search} onClick={run}>{busy?'Finding potential customers…':'Find potential customers'}</button></div>
    {!allowance?.available&&<p>{allowance?.message||'Checking search access…'}</p>}<small>{allowance?.configured&&`${allowance.remaining} businesses left in your monthly search allowance.`}</small>
   </>}
  </section>}
  {!editing&&searches.length>0&&<details className="dw-history"><summary>Your recent and saved searches ({searches.length})</summary>{searches.map(s=><article key={s.id}><div><b>{s.criteria.industry} · {s.criteria.city}, {s.criteria.state}</b><p>{words(s.status)} · {new Date(s.created_at).toLocaleString()} {s.saved?'· Saved search':''}</p></div><button onClick={()=>{setError('');setCriteria({...emptyCriteria,...s.criteria});setTab('results');setEditing(false);reset();void loadResult(s.id).catch((e:any)=>setError(e.message))}}>Resume search</button><button aria-label={`${s.saved?'Unsave':'Save'} search ${s.criteria.industry} ${s.criteria.city}`} onClick={()=>api.discoverySaveSearch(s.id,!s.saved).then(()=>loadHistory()).catch((e:any)=>setError(e.message))}>{s.saved?'Unsave search':'Save search'}</button></article>)}</details>}
  {!editing&&(result||saved.length>0||!home)&&<section className="dw-results" aria-label="Potential customer results">
   <div className="dw-tabs" role="group" aria-label="Potential customer view"><button aria-pressed={tab==='results'} onClick={()=>{setTab('results');setSelected([])}}>Businesses found</button><button aria-pressed={tab==='saved'} onClick={()=>{setTab('saved');setSelected([])}}>Saved potential customers ({saved.length})</button><button onClick={()=>{setEditing(true);setStep(0)}}>Start a new search</button></div>
   {tab==='results'&&result&&<div className="dw-search-summary"><strong>{result.criteria.industry} in {result.criteria.city}, {result.criteria.state}</strong><p>{words(result.status)} · {(result.businesses||[]).length} unique businesses · {result.duplicates||0} duplicates removed {result.skipped?`· ${result.skipped} incomplete records skipped`:''}</p>{result.status==='SEARCHING'&&<p role="status">Searching provider records. Your criteria are unchanged; this can take up to 90 seconds. You can return and resume this search.</p>}{result.status==='PARTIAL'&&<p role="status">Partial results: review the records available. Incomplete records were skipped; retry uses the same criteria unless you edit them.</p>}{result.error&&<p role="alert">{result.error}</p>}</div>}
   {tab==='results'&&result&&<div className="dw-actions"><button aria-pressed={guided} onClick={()=>setGuided(x=>!x)}>{guided?'View all businesses':'Review one at a time'}</button></div>}
   {(!guided||tab==='saved')&&<><details><summary>Filter and sort these businesses</summary><div className="dw-fields dw-filters"><label>Search these results<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Your decision<select value={decision} onChange={e=>setDecision(e.target.value)}>{['ALL','UNREVIEWED','QUALIFIED','NEEDS_RESEARCH','DISQUALIFIED'].map(x=><option key={x} value={x}>{decisionLabels[x]||'All decisions'}</option>)}</select></label><label>Contact availability<select value={contact} onChange={e=>setContact(e.target.value)}><option value="ALL">All</option><option value="YES">Contact details available</option><option value="NO">No contact details</option></select></label><label>How well it matches<select value={fit} onChange={e=>setFit(e.target.value)}><option value="WITHIN">Hide confirmed mismatches</option><option value="ALL">Show all provider results</option></select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="fit">Most matching details</option><option value="name">Business name</option><option value="recent">Most recently found</option></select></label></div></details>
   <p role="status">{visible.length} of {allRows.length} shown. {active.join(' · ')||'No additional filters'}</p><div className="dw-actions"><button onClick={reset}>Reset result filters</button><button disabled={!selected.length||busy} onClick={saveSelected}>Save {selected.length} selected businesses</button>{selected.length>0&&<button onClick={()=>{onContext?.(selected);setMessage('Open Skye to compare the selected businesses.')}}>Compare with Skye</button>}</div>
   {ready&&visible.length===0&&result?.status!=='SEARCHING'&&<div className="dw-empty"><h3>{tab==='saved'?'No saved businesses match these filters.':result?'No businesses match the current view.':'Start a search to find businesses.'}</h3><p>Reset result filters, lower your minimum rating or review count, or edit the industry and location. Criteria change only when you choose them. Missing evidence is not a confirmed match.</p>{!home&&<button onClick={()=>onNavigate('Home')}>Edit search criteria</button>}</div>}
   <div className="dw-list">{visible.map((row:any)=>{const q=row.assessment||{};return <article key={row.id}>
    <div className="dw-row-top"><button className="dw-business-open" onClick={()=>open(row)}><h3>{row.name||row.company}</h3><span>{[row.category,[row.city,row.state].filter(Boolean).join(', ')].filter(Boolean).join(' · ')||'Industry or location not recorded'}</span></button><span className="dw-badge">{decisionLabels[row.decision]}{row.saved?' · Saved':''}</span></div>
    <p><strong>{fitLabel(q.label)}</strong> · {(q.matches||[]).slice(0,2).join(' · ')||'We don’t have enough information to explain a match yet'}</p><p>{q.contact_paths?.length?`Available: ${q.contact_paths.join(', ')} (not verified)`:'No contact details recorded yet'}</p><p className="dw-unknown">Not known: {(q.missing_information||[]).slice(0,2).join(' · ')}</p>
    <div className="dw-actions"><button onClick={()=>open(row)}>{row.saved?'View next steps':row.decision==='UNREVIEWED'?'Take a look':row.decision==='NEEDS_RESEARCH'?'Take another look':'Review my decision'}</button>{row.saved&&<details><summary>Advanced tools</summary><button onClick={()=>openSaved(row)}>Open full saved record</button></details>}{typeof row.id==='number'&&row.decision==='QUALIFIED'&&!row.saved&&<label className="dw-check"><input type="checkbox" checked={selected.includes(row.id)} onChange={e=>setSelected(x=>e.target.checked?[...x,row.id]:x.filter(id=>id!==row.id))}/>Select to save</label>}</div>
   </article>})}</div></>}
   {guided&&tab==='results'&&result&&result.status!=='SEARCHING'&&<GuidedReview key={result.id} businesses={allRows} campaign={activeCampaign.current} searchId={result.id} onUpdated={updateRow} onOpen={open} onBrowse={()=>setGuided(false)} onNewSearch={()=>{setEditing(true);setStep(0)}}/>}
  </section>}
  {home&&<details className="dw-secondary"><summary>Advanced sales tools and follow-ups</summary><div className="dw-actions"><button onClick={()=>onNavigate('Calendar')}>Open follow-ups</button><button onClick={()=>onNavigate('Leads')}>View pipeline</button><button onClick={()=>onNavigate('Prospects')}>Browse saved businesses</button></div></details>}
  {opened&&<QualificationDetail lead={opened} campaign={activeCampaign.current} search={tab==='results'?result?.id:undefined} onClose={close} onUpdated={updateRow} onOutreach={()=>{close();onNavigate('Up Next')}} onSaved={()=>{void openSaved(opened)}}/>}
 </div>
}

function QualificationDetail({lead,campaign,search,onClose,onUpdated,onOutreach,onSaved}:{lead:any;campaign:string;search?:string;onClose:()=>void;onUpdated:(lead:any)=>void;onOutreach:()=>void;onSaved:()=>void}){
 const [reason,setReason]=useState(lead.reason||''),[notes,setNotes]=useState(lead.notes||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[undo,setUndo]=useState<any>(null),[notice,setNotice]=useState(''),[draft,setDraft]=useState(''),[skye,setSkye]=useState<any>(null);
 useEffect(()=>{setReason(lead.reason||'');setNotes(lead.notes||'')},[lead.revision]);
 const ref=useSurfaceDialog(true,onClose),q=lead.assessment||{};
 const perform=async(action:()=>Promise<any>)=>{setBusy(true);setError('');try{const result=await action();const detail=await api.discoveryDetail(lead.id,search);onUpdated(detail);return result}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const decide=async(outcome:string)=>{const result=await perform(()=>api.discoveryDecide(lead.id,{decision:outcome,reason:reason.trim()||`My decision: ${decisionLabels[outcome]}.`,notes,revision:lead.revision}));if(result){setUndo({event_id:result.undo_event,revision:result.revision});setNotice('Your decision was saved automatically.')}};
 return createPortal(<div className="dw-modal" ref={ref} role="dialog" aria-modal="true" aria-labelledby="dw-detail-title"><div className="dw-detail"><header><div><small>POTENTIAL CUSTOMER</small><h2 id="dw-detail-title">{lead.name}</h2><p>{[lead.category,lead.city,lead.state].filter(Boolean).join(' · ')}</p></div><button aria-label="Close business details" onClick={onClose}>×</button></header>
  <p><strong>{fitLabel(q.label)}</strong> · {decisionLabels[lead.decision]}{lead.saved?' · Saved':''}</p><p>{q.score_meaning}</p>
  <h3>Why it might fit</h3><ul>{(q.matches||[]).length?q.matches.map((x:string)=><li key={x}>{x}</li>):<li>No match is confirmed by the recorded criteria.</li>}</ul>
  <div className="dw-evidence">{(q.criteria||[]).map((x:any)=><article key={x.criterion}><b>{x.criterion}</b><span>{words(x.status)}</span><p>Target: {x.target}</p><p>Recorded: {x.value}</p></article>)}</div>
  <details><summary>Ask Skye about this business</summary><div className="dw-actions">{['Why does this business fit?','What information is missing?'].map(question=><button key={question} disabled={busy} onClick={async()=>{const answer=await perform(()=>api.discoveryExplain({campaign,search_id:search,business_ids:[lead.id],question}));if(answer)setSkye(answer)}}>{question}</button>)}</div>{skye&&<div aria-live="polite"><p><b>Skye:</b> {skye.reply}</p>{skye.businesses?.map((b:any)=><div key={b.id}><p>What matches: {b.known.join(' · ')||'No confirmed match yet'}</p><p>What to check: {b.missing.join(' · ')}</p><p>My suggestion: {decisionLabels[b.suggested_decision]}. {b.explanation}</p>{b.sources.map((source:any)=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</div>)}</div>}</details>
  <h3>What we don’t know</h3><ul>{(q.missing_information||[]).map((x:string)=><li key={x}>{x}</li>)}</ul>
  {(q.signals||[]).length>0&&<><h3>Things to check</h3><ul>{q.signals.map((x:any,i:number)=><li key={i}>{x.signal}: {x.evidence}</li>)}</ul></>}
  <h3>How to learn more or contact them</h3><p>{q.contact_readiness}. No decision-maker or contact verification is implied.</p><div className="dw-actions">{lead.phone&&<a href={`tel:${String(lead.phone).replace(/[^+\d]/g,'')}`}>Call {lead.phone}</a>}{lead.email&&<a href={`mailto:${lead.email}`}>Email {lead.email}</a>}{safeLink(lead.website)&&<a href={safeLink(lead.website)} target="_blank" rel="noreferrer">Business website ↗</a>}{(q.sources||[]).filter((s:any)=>safeLink(s.url)).map((s:any)=><a key={s.url} href={safeLink(s.url)} target="_blank" rel="noreferrer">{s.label} ↗</a>)}</div><p>Listing fetched: {lead.discovered_at?new Date(lead.discovered_at).toLocaleString():'Not recorded'}. Website links are references; page content has not been checked by this search.</p>
  <section className="dw-decision"><h3>Does this look worth contacting?</h3><p>You can change your mind later. A match does not mean they want to buy.</p><div className="dw-actions" role="group" aria-label="Your decision">{['QUALIFIED','NEEDS_RESEARCH','DISQUALIFIED'].map(x=><button key={x} aria-pressed={lead.decision===x} disabled={busy} onClick={()=>decide(x)}>{decisionLabels[x]}</button>)}</div><details><summary>Add a reason or note (optional)</summary><label>Why do you think that?<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Anything to remember?<textarea maxLength={3000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={busy||lead.decision==='UNREVIEWED'} onClick={()=>decide(lead.decision)}>Save my notes</button></details>{notice&&<p role="status">{notice}</p>}{undo&&<button disabled={busy} onClick={async()=>{const result=await perform(()=>api.discoveryUndo(lead.id,undo));if(result){setUndo(null);setNotice('Your last decision was undone.')}}}>Undo last decision</button>}</section>
  {error&&<p role="alert">{error}</p>}
  {lead.decision==='QUALIFIED'&&!lead.saved&&<button disabled={busy} className="dw-primary" onClick={async()=>{const result=await perform(()=>api.discoverySave(lead.id));if(result)setNotice('Business saved. You can check its website or prepare a first message below.')}}>Save this potential customer</button>}
  {lead.saved&&<section className="dw-next"><h3>Saved. What would you like to do next?</h3><p>No rush—keep it saved until you’re ready.</p><div className="dw-actions">{safeLink(lead.website)&&<a href={safeLink(lead.website)} target="_blank" rel="noreferrer">Check their website ↗</a>}<button disabled={busy} onClick={async()=>{const result=await perform(()=>api.discoveryExplain({campaign,search_id:search,business_ids:[lead.id],question:'Draft a first message.'}));if(result)setDraft(result.draft||result.reply)}}>Help draft a first message</button><details><summary>Advanced sales tools</summary><button onClick={onSaved}>Open full saved record</button></details></div>{draft&&<div className="dw-draft"><h3>A starting draft for you to edit</h3><p style={{whiteSpace:'pre-wrap'}}>{draft}</p><p>Review the message and contact details before sending. Nothing has been sent.</p></div>}{lead.decision==='QUALIFIED'&&q.contact_paths?.length>0&&<button disabled={busy} onClick={async()=>{const result=await perform(()=>api.discoveryOutreach(lead.id));if(result)onOutreach()}}>Prepare to contact them</button>}</section>}
  <details><summary>Your past decisions ({lead.history?.length||0})</summary>{(lead.history||[]).map((x:any)=><p key={x.id}>{new Date(x.created_at).toLocaleString()} · {decisionLabels[x.decision]} · {x.reason}</p>)}</details>
 </div></div>,document.body);
}
