import React,{useEffect,useState} from 'react';
import {api} from './api';
export function DiscoveryProfile({onDiscover,onMore,onHelp=onDiscover}:{onDiscover:()=>void;onMore:()=>void;onHelp?:()=>void}){
 const [target,setTarget]=useState<any>(null),[form,setForm]=useState({offer:'',industry:'',city:'',state:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=()=>{setError('');api.discoveryTarget().then(t=>{setTarget(t);const location=String(t.profile?.geography?.[0]||'').split(',');setForm({offer:t.profile?.offer||'',industry:t.criteria?.industry||t.profile?.business_types?.[0]||'',city:t.criteria?.city||location[0]||'',state:t.criteria?.state||location[1]?.trim()||''})}).catch(()=>setError('Your profile could not load. Try again.'))};
 useEffect(load,[]);
 const save=async()=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await api.discoverySaveTarget({...target.criteria,industry:form.industry.trim(),city:form.city.trim(),state:form.state.trim().toUpperCase()});const next=await api.saveIcpProfile({profile:{...target.profile,offer:form.offer.trim(),business_types:[form.industry.trim(),...(target.profile?.business_types||[]).slice(1)],target_industries:[form.industry.trim(),...(target.profile?.target_industries||[]).slice(1)],geography:[`${form.city.trim()}, ${form.state.trim().toUpperCase()}`,...(target.profile?.geography||[]).slice(1)]},weights:target.weights,completed:true});setTarget({...target,...next});setNotice('Profile saved. Ready to find customers.')}catch(e:any){setError(`Profile couldn’t finish saving. Some fields may have saved; retry to finish. ${e.message||''}`)}finally{setBusy(false)}};
 return <section className="kp-discovery-profile"><header><img src="/avatars/skye.png" alt="Skye"/><div><h2>Your starting point</h2><p>A few words help us look in the right places.</p></div></header>{error&&<p role="alert">{error}{!target&&<button onClick={load}>Try again</button>}</p>}{!target&&!error&&<p role="status">Loading profile…</p>}{target&&<form onSubmit={e=>{e.preventDefault();void save()}}><label>What do you sell?<input required maxLength={500} value={form.offer} onChange={e=>setForm({...form,offer:e.target.value})} placeholder="For example, photos and social content"/></label><label>Who could use it?<input required maxLength={120} value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})} placeholder="For example, restaurants"/></label><div className="kp-profile-area"><label>City<input required maxLength={120} value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Orlando"/></label><label>State<input required pattern="[A-Za-z]{2}" maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})} placeholder="FL"/></label></div><button className="dw-primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button><p role="status">{notice}</p></form>}<button disabled={busy} onClick={onDiscover}>Find customers →</button><details><summary>Need help or more options?</summary><p>Skye can help you choose a starting business type. You can also use the short questions in Discover.</p><button onClick={onHelp}>Help me figure this out</button><button onClick={onMore}>Outreach, deals & settings</button></details></section>;
}
