import {BusinessHero} from './BusinessHero';
import React from 'react';
type Preview={label:string;title:string;summary?:string;business?:any};
type Props={activeKey:string|number;children:React.ReactNode;previous?:Preview;next?:Preview;onPrevious?:()=>void;onNext?:()=>void};
function SideCard({card,side}:{card?:Preview;side:string}){return <div className={`kp-carousel-preview kp-carousel-${side}`} aria-hidden="true" inert>{card?.business?<><BusinessHero business={card.business} compact/><h3>{card.title}</h3><p>{card.summary}</p><div className="kp-preview-evidence"><p>⌕ {card.business.assessment?.matches?.slice(0,2).join(' · ')||'Match not confirmed'}</p><p>✓ Contact: {card.business.assessment?.contact_paths?.join(', ')||'Not recorded'}</p><p>? {card.business.assessment?.missing_information?.[0]||'Review the evidence'}</p></div></>:<><img className="kp-preview-skye" src="/avatars/skye.png" alt=""/><small>{card?.label||'Your guide'}</small><h3>{card?.title||'One step at a time'}</h3><p>{card?.summary||'Skye helps you check each business before you decide.'}</p></>}</div>}
/** Adjacent cards are inert previews. Browsing never assigns a decision. */
export function FocusCarousel({activeKey,children,previous,next,onPrevious,onNext}:Props){
 const handleKey=(e:React.KeyboardEvent<HTMLDivElement>)=>{if(e.target!==e.currentTarget)return;if(e.key==='ArrowLeft'&&onPrevious){e.preventDefault();onPrevious()}if(e.key==='ArrowRight'&&onNext){e.preventDefault();onNext()}};
 return <div className="kp-carousel" role="region" aria-roledescription="carousel" aria-label="Guided discovery cards" tabIndex={0} onKeyDown={handleKey}><div className="kp-carousel-stage"><SideCard card={previous} side="previous"/><div className="kp-carousel-active" key={activeKey} role="group" aria-roledescription="slide">{children}</div><SideCard card={next} side="next"/></div><div className="kp-carousel-controls"><button aria-label="Previous card" disabled={!onPrevious} onClick={onPrevious}>‹</button><span>One business. One decision.</span><button aria-label="Next card" disabled={!onNext} onClick={onNext}>›</button></div></div>;
}
