import React,{useEffect,useState} from 'react';
import {api} from './api';
import './Lifecycle.css';

const money=(value:any)=>`$${Number(value||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const label=(value:any)=>String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const when=(value:any)=>value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not set';

export function LifecycleNotice(){
 const [show,setShow]=useState(()=>{try{return localStorage.getItem('kp-lifecycle-notice')!=='seen'}catch{return true}});
 if(!show)return null;
 return <div className="lc-notice" role="status"><div><b>KP Sales OS has a new sales workflow.</b><span>Your existing data is still here - contacts are now organized into Prospects, Leads, and Customers.</span></div><button onClick={()=>{try{localStorage.setItem('kp-lifecycle-notice','seen')}catch{}setShow(false)}} aria-label="Dismiss workflow notice">Got it</button></div>
}

function Empty({title,text}:{title:string;text:string}){return <div className="card lc-empty"><h3>{title}</h3><p>{text}</p></div>}

export function HomeWorkspace({campaign,onNavigate,onTour}:{campaign:string;onNavigate:(page:string)=>void;onTour:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{setData(null);setError('');api.commandCenter(campaign).then(setData).catch(()=>setError('Your command center could not load. Try refreshing.'))},[campaign]);
 if(error)return <Empty title="Home is temporarily unavailable" text={error}/>;
 if(!data)return <div className="card lc-empty">Loading today's priorities...</div>;
 const priorities=[
  {name:'Prospects needing outreach',value:data.prospects_needing_outreach?.length||0,page:'Prospects',hint:'Start a conversation'},
  {name:'Follow-ups due',value:data.followups_due?.length||0,page:'Calendar',hint:'Keep momentum'},
  {name:'Active leads',value:data.active_leads||0,page:'Leads',hint:'Work the deal'},
  {name:'Awaiting decisions',value:data.awaiting_decision?.length||0,page:'Leads',hint:'Close the loop'},
 ];
 return <div className="lc-page"><LifecycleNotice/><section className="lc-hero"><p className="lc-eyebrow">YOUR SALES COMMAND CENTER</p><h2>Who needs your attention today?</h2><p>Work the next useful action. The numbers update from your contacts and deals.</p><button onClick={onTour}>Show me how Sales OS works</button></section><div className="lc-priority-grid">{priorities.map(x=><button key={x.name} onClick={()=>onNavigate(x.page)}><strong>{x.value}</strong><span>{x.name}</span><small>{x.hint} →</small></button>)}</div><div className="lc-home-grid"><section className="card"><div className="lc-section-head"><div><p className="lc-eyebrow">DO THIS NEXT</p><h3>Today's follow-ups</h3></div><button onClick={()=>onNavigate('Calendar')}>View all</button></div>{data.followups_due?.length?data.followups_due.slice(0,4).map((x:any)=><div className="lc-list-row" key={x.id}><div><b>{x.company||x.name}</b><small>{x.next_action?.action||'Follow up'} · {when(x.next_action?.due_at)}</small></div><button onClick={()=>onNavigate('Prospects')}>Open</button></div>):<p className="lc-muted">No follow-ups are due.</p>}</section><section className="card"><p className="lc-eyebrow">PIPELINE SNAPSHOT</p><div className="lc-money"><span><strong>{money(data.pipeline_value)}</strong><small>Active pipeline</small></span><span><strong>{money(data.revenue_collected)}</strong><small>Revenue collected</small></span></div><button className="lc-primary" onClick={()=>onNavigate('Sales & Revenue')}>Open Sales & Revenue →</button></section></div></div>
}

export function ProspectWorkspace({campaign,onNavigate,onOpenContact}:{campaign:string;onNavigate:(page:string)=>void;onOpenContact:(contact:any)=>void}){
 const [rows,setRows]=useState<any[]|null>(null),[convert,setConvert]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>api.lifecycleContacts('PROSPECT',campaign).then(setRows).catch(()=>setRows([]));useEffect(()=>{void load()},[campaign]);
 const promote=async(contact:any)=>{setBusy(true);setMessage('');try{await api.convertToLead(contact.id,{});setConvert(null);setMessage(`${contact.company||contact.name} moved to Leads.`);load()}catch(e:any){setMessage(e.message||'Could not convert this prospect.')}finally{setBusy(false)}};
 return <div className="lc-page"><LifecycleNotice/><section className="lc-toolbar"><div><p className="lc-eyebrow">OUTBOUND WORKSPACE</p><h2>Prospects</h2><p>People you found and are trying to get in front of.</p></div><div><button onClick={()=>onNavigate('Add Prospect')}>+ Add prospect</button><button onClick={()=>onNavigate('Lead Generator')}>Find prospects</button><button className="lc-primary" onClick={()=>onNavigate('Up Next')}>Start selling</button></div></section>{message&&<p className="lc-feedback">{message}</p>}{rows===null?<div className="card lc-empty">Loading prospects...</div>:rows.length?<div className="lc-contact-list">{rows.map(contact=><article className="card lc-contact" key={contact.id}><div className="lc-contact-main"><div><span className="lc-status">{label(contact.sales_status||'NEW')}</span><h3>{contact.company||contact.name}</h3>{contact.company&&contact.name!==contact.company&&<p>{contact.name}</p>}</div><div className="lc-contact-meta"><span><small>Contact</small>{contact.email||contact.phone||'Not added'}</span><span><small>Added</small>{when(contact.created_at)}</span><span><small>Last activity</small>{when(contact.last_activity_at)}</span><span><small>Next action</small>{contact.next_action?.action||'Choose next step'}{contact.next_action?.due_at&&<em>{when(contact.next_action.due_at)}</em>}</span></div></div><div className="lc-actions"><button onClick={()=>onOpenContact({...contact,prospect_id:contact.id})}>Log contact / notes</button><button onClick={()=>onOpenContact({...contact,prospect_id:contact.id})}>Schedule consultation</button><button className="lc-primary" onClick={()=>setConvert(contact.id)}>Convert to Lead</button></div>{convert===contact.id&&<div className="lc-confirm"><p>Move this contact into the active sales pipeline? Their history and consultations will stay attached.</p><button onClick={()=>setConvert(null)}>Cancel</button><button disabled={busy} className="lc-primary" onClick={()=>promote(contact)}>{busy?'Converting...':'Confirm conversion'}</button></div>}</article>)}</div>:<Empty title="No prospects yet" text="Add someone you met or find prospects to begin your outbound workflow."/>}</div>
}

const stages=['NEW_LEAD','CONSULTATION','PROPOSAL','DECISION','WON','LOST'];
export function LeadsWorkspace({campaign,onOpenContact}:{campaign:string;onOpenContact:(contact:any)=>void}){
 const [rows,setRows]=useState<any[]|null>(null),[selected,setSelected]=useState<any>(null);
 const load=()=>api.deals(campaign).then(setRows).catch(()=>setRows([]));useEffect(()=>{void load()},[campaign]);
 return <div className="lc-page"><LifecycleNotice/><section className="lc-toolbar"><div><p className="lc-eyebrow">ACTIVE SALES PIPELINE</p><h2>Leads & Deals</h2><p>Interest became an opportunity. Keep the next action visible.</p></div><div className="lc-kpi"><strong>{money(rows?.filter(x=>x.status==='ACTIVE').reduce((n,x)=>n+Number(x.deal_value||0),0))}</strong><small>Active pipeline</small></div></section>{rows===null?<div className="card lc-empty">Loading pipeline...</div>:<div className="lc-pipeline">{stages.map(stage=><section key={stage}><header><b>{label(stage)}</b><span>{rows.filter(x=>x.stage===stage).length}</span></header><div>{rows.filter(x=>x.stage===stage).map(deal=><button className="lc-deal-card" key={deal.id} onClick={()=>setSelected(deal)}><b>{deal.contact?.company||deal.contact?.name}</b><span>{deal.name}</span><strong>{money(deal.deal_value)}</strong><small>{deal.next_action||'Set next action'}{deal.next_action_at&&` · ${when(deal.next_action_at)}`}</small></button>)}</div></section>)}</div>}{selected&&<DealPanel dealId={selected.id} onClose={()=>{setSelected(null);load()}} onOpenContact={onOpenContact}/>}</div>
}

function DealPanel({dealId,onClose,onOpenContact}:{dealId:number;onClose:()=>void;onOpenContact:(contact:any)=>void}){
 const [deal,setDeal]=useState<any>(null),[tab,setTab]=useState('Overview'),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=()=>api.deal(dealId).then(setDeal);useEffect(()=>{void load()},[dealId]);
 const update=async(body:any)=>{setSaving(true);setMessage('');try{await api.updateDeal(dealId,body);await load();setMessage('Deal updated.')}catch{setMessage('Could not update this deal.')}finally{setSaving(false)}};
 if(!deal)return <div className="lc-modal"><div className="lc-panel">Loading deal...</div></div>;
 return <div className="lc-modal" role="dialog" aria-modal="true"><button className="lc-modal-backdrop" onClick={onClose} aria-label="Close deal"/><section className="lc-panel"><header><div><p className="lc-eyebrow">{label(deal.stage)}</p><h2>{deal.contact.company||deal.contact.name}</h2><p>{deal.name}</p></div><button onClick={onClose} aria-label="Close">×</button></header><div className="lc-deal-summary"><span><small>Deal value</small><strong>{money(deal.deal_value)}</strong></span><span><small>Stage</small><strong>{label(deal.stage)}</strong></span><span><small>Expected close</small><strong>{deal.expected_close||'Not set'}</strong></span><span><small>Next action</small><strong>{deal.next_action||'Not set'}</strong></span></div><div className="lc-actions"><button onClick={()=>onOpenContact({...deal.contact,prospect_id:deal.contact.id})}>Log contact</button><button onClick={()=>onOpenContact({...deal.contact,prospect_id:deal.contact.id})}>Schedule consultation</button><button onClick={()=>setTab('Overview')}>Edit deal</button><button onClick={()=>update({stage:'WON'})}>Mark Won</button><button onClick={()=>update({stage:'LOST'})}>Mark Lost</button></div><nav className="lc-tabs">{['Overview','Activity','Consultation','Notes'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{message&&<p className="lc-feedback">{message}</p>}{tab==='Overview'?<DealForm deal={deal} saving={saving} update={update}/>:tab==='Activity'?<div className="lc-timeline">{deal.timeline?.length?deal.timeline.map((x:any,i:number)=><div key={i}><i/><span><b>{label(x.type)}</b><small>{when(x.at)}</small></span></div>):<p>No activity yet.</p>}</div>:tab==='Consultation'?<div className="lc-panel-section"><h3>Consultation</h3><p>Scheduling stays attached to this contact and returns you to the deal afterward.</p><button className="lc-primary" onClick={()=>onOpenContact({...deal.contact,prospect_id:deal.contact.id})}>Schedule or review consultation</button></div>:<div className="lc-panel-section"><h3>Notes</h3><p>{deal.contact.notes||'No notes yet.'}</p><button onClick={()=>onOpenContact({...deal.contact,prospect_id:deal.contact.id})}>Add or edit notes</button></div>}</section></div>
}

function DealForm({deal,saving,update}:{deal:any;saving:boolean;update:(body:any)=>void}){
 const [form,setForm]=useState(()=>({name:deal.name,stage:deal.stage,deal_value:deal.deal_value??'',revenue_collected:deal.revenue_collected??0,expected_close:deal.expected_close||'',next_action:deal.next_action||'',next_action_at:(deal.next_action_at||'').slice(0,16)}));
 return <div className="lc-form-grid"><label>Opportunity<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Deal value<input type="number" min="0" value={form.deal_value} onChange={e=>setForm({...form,deal_value:e.target.value})}/></label><label>Revenue collected<input type="number" min="0" value={form.revenue_collected} onChange={e=>setForm({...form,revenue_collected:e.target.value})}/></label><label>Expected close<input type="date" value={form.expected_close} onChange={e=>setForm({...form,expected_close:e.target.value})}/></label><label>Next action date<input type="datetime-local" value={form.next_action_at} onChange={e=>setForm({...form,next_action_at:e.target.value})}/></label><label className="lc-wide">Next action<input value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})}/></label><button disabled={saving} className="lc-primary" onClick={()=>update({...form,deal_value:form.deal_value===''?null:Number(form.deal_value),revenue_collected:Number(form.revenue_collected||0),next_action_at:form.next_action_at?new Date(form.next_action_at).toISOString():null})}>{saving?'Saving...':'Save deal'}</button></div>
}

export function CustomersWorkspace({campaign}:{campaign:string}){
 const [rows,setRows]=useState<any[]|null>(null),[opening,setOpening]=useState<number|null>(null),[name,setName]=useState('');
 const load=()=>api.lifecycleContacts('CUSTOMER',campaign).then(async contacts=>{const deals=await api.deals(campaign);setRows(contacts.map(c=>({...c,deals:deals.filter(d=>d.contact?.id===c.id)})))}).catch(()=>setRows([]));useEffect(()=>{void load()},[campaign]);
 const create=async(contact:any)=>{await api.newOpportunity(contact.id,{name});setOpening(null);setName('');load()};
 return <div className="lc-page"><LifecycleNotice/><section className="lc-toolbar"><div><p className="lc-eyebrow">RELATIONSHIPS THAT BOUGHT</p><h2>Customers</h2><p>One contact, complete history, and room for repeat opportunities.</p></div></section>{rows===null?<div className="card lc-empty">Loading customers...</div>:rows.length?<div className="lc-customer-grid">{rows.map(c=>{const won=c.deals.filter((d:any)=>d.status==='WON');return <article className="card" key={c.id}><span className="lc-status">Customer since {c.customer_since?new Date(c.customer_since).toLocaleDateString():'-'}</span><h3>{c.company||c.name}</h3><div className="lc-money"><span><strong>{money(won.reduce((n:number,d:any)=>n+Number(d.deal_value||0),0))}</strong><small>Lifetime contracted</small></span><span><strong>{money(won.reduce((n:number,d:any)=>n+Number(d.revenue_collected||0),0))}</strong><small>Collected</small></span></div><p className="lc-muted">{c.deals.length} opportunity{c.deals.length===1?'':'ies'} · Last contact {when(c.last_activity_at)}</p><button className="lc-primary" onClick={()=>setOpening(c.id)}>+ New opportunity</button>{opening===c.id&&<div className="lc-confirm"><input placeholder="Opportunity name" value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>setOpening(null)}>Cancel</button><button onClick={()=>create(c)}>Create</button></div>}</article>})}</div>:<Empty title="No customers yet" text="When a deal is marked Won, the contact will appear here automatically."/>}</div>
}

export function RevenueWorkspace({campaign}:{campaign:string}){
 const [period,setPeriod]=useState('30d'),[data,setData]=useState<any>(null);useEffect(()=>{setData(null);api.salesRevenue(campaign,period).then(setData)},[campaign,period]);
 if(!data)return <div className="card lc-empty">Loading sales and revenue...</div>;
 const metrics=[['Active pipeline',data.active_pipeline_value],['Revenue won',data.revenue_won],['Revenue collected',data.revenue_collected],['Revenue lost',data.revenue_lost],['Average deal',data.average_deal_size]];
 return <div className="lc-page"><section className="lc-toolbar"><div><p className="lc-eyebrow">SALES & REVENUE</p><h2>Money follows the deal.</h2><p>Contracted value and collected revenue stay separate.</p></div><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="week">Week</option><option value="month">Month</option><option value="30d">Last 30 days</option><option value="year">Year</option></select></section><div className="lc-revenue-metrics">{metrics.map(([name,value])=><div key={name}><strong>{money(value)}</strong><span>{name}</span></div>)}<div><strong>{Number(data.close_rate||0).toFixed(0)}%</strong><span>Close rate</span></div><div><strong>{data.deals_won}</strong><span>Deals won</span></div></div><section className="card"><h3>Deals</h3><div className="lc-table"><table><thead><tr><th>Contact</th><th>Opportunity</th><th>Stage</th><th>Deal value</th><th>Collected</th><th>Expected close</th><th>Status</th></tr></thead><tbody>{data.deals.map((d:any)=><tr key={d.id}><td>{d.company||d.contact_name}</td><td>{d.name}</td><td>{label(d.stage)}</td><td>{money(d.deal_value)}</td><td>{money(d.revenue_collected)}</td><td>{d.expected_close||'-'}</td><td>{label(d.status)}</td></tr>)}</tbody></table></div></section></div>
}
