import React,{useEffect,useState} from 'react';
import {api} from './api';

const label=(value:any)=>String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const date=(value:any)=>value?new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not evaluated yet';

export function RescorePanel({prospect,onUpdated}:{prospect:any;onUpdated?:(result:any)=>void}){
 const id=Number(prospect.prospect_id??prospect.id),[history,setHistory]=useState<any[]>([]),[profile,setProfile]=useState<any>(null),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=()=>Promise.all([api.scoreHistory(id),api.icpProfile()]).then(([rows,icp])=>{setHistory(rows);setProfile(icp)}).catch(()=>{});
 useEffect(()=>{if(id)void load()},[id]);
 const run=async(refresh:boolean)=>{setBusy(refresh?'refresh':'rescore');setError('');try{const value=await api.rescoreLead(id,refresh);setResult(value);onUpdated?.(value);await load()}catch(e:any){setError(e.message||'Rescoring could not finish.')}finally{setBusy('')}};
 const latest=result||history[0]?.explanation||{},score=latest.new_score??prospect.icp_score??prospect.score,stale=profile?.version&&prospect.icp_version&&Number(profile.version)>Number(prospect.icp_version);
 return <section className="rescore-panel"><header><div><p className="eyebrow">ICP EVALUATION</p><h3>{score??'—'} Match</h3><small>Last evaluated: {date(latest.scored_at||prospect.last_scored_at)}</small>{(latest.last_enriched_at||prospect.last_enriched_at)&&<small>Evidence checked: {date(latest.last_enriched_at||prospect.last_enriched_at)}</small>}</div>{stale&&<span className="rescore-stale">ICP changed · Rescore recommended</span>}</header><div className="rescore-actions"><button disabled={!!busy} onClick={()=>run(false)}>{busy==='rescore'?'Rescoring…':'Rescore'}<small>Use current evidence</small></button><button className="primary" disabled={!!busy} onClick={()=>run(true)}>{busy==='refresh'?'Checking sources…':'Refresh & Rescore'}<small>Check website and socials</small></button></div>{error&&<p className="rescore-error" role="alert">{error}</p>}{result&&<div className="rescore-result"><div className="rescore-change"><span><small>Previous</small><b>{result.previous_score}</b></span><strong aria-label={`Score change ${result.score_delta}`}>{result.score_delta>0?'+':''}{result.score_delta}</strong><span><small>New score</small><b>{result.new_score}</b></span></div><h4>{result.score_delta>=5?'This lead moved up.':result.score_delta<=-5?'This lead moved down.':'The score stayed similar.'}</h4>{result.matches?.length>0&&<p><b>Why:</b> {result.matches.slice(0,3).join(' · ')}</p>}{result.signals?.length>0&&<p><b>Signals:</b> {result.signals.slice(0,3).join(' · ')}</p>}{result.missing_information?.length>0&&<p><b>Still missing:</b> {result.missing_information.slice(0,3).join(' · ')}</p>}<p><b>Best move:</b> {result.recommended_action}</p>{result.enrichment_errors?.length>0&&<p className="rescore-note">Some public sources were unavailable. The lead was scored with the evidence KP Sales OS could verify.</p>}<details><summary>View evidence</summary>{result.evidence?.length?<div className="evidence-list">{result.evidence.map((item:any,index:number)=><article key={`${item.signal_type}-${index}`}><header><b>{item.signal_value}</b><span>{item.confidence} CONFIDENCE</span></header><p>{item.evidence_text}</p><a href={item.source_url} target="_blank" rel="noreferrer">{label(item.source_type)} source ↗</a></article>)}</div>:<p>No new supported public evidence was found. Missing evidence was treated as unknown.</p>}</details></div>}{history.length>0&&<details className="rescore-history"><summary>Scoring history</summary>{history.slice(0,6).map(row=><div key={row.id}><span>{date(row.created_at)}</span><b>{row.previous_score} → {row.new_score}</b><small>{label(row.trigger_type)}{row.sources?.length?` · ${row.sources.map(label).join(' + ')}`:''}</small></div>)}</details>}</section>
}
