import React, {useEffect, useMemo, useState} from 'react';
import {api, QueueItem} from './api';
import {CalendarGrid, Icon} from './AppExperience';

type Prospect = QueueItem & {business_name?:string;city?:string;state?:string;last_activity_at?:string;next_action?:{action?:string;due_at?:string}};
const label=(s?:string)=>(s||'NOT_CONTACTED').replace(/_/g,' ').toLowerCase();
const name=(p:Prospect)=>p.business_name||p.name||p.business||'Unnamed prospect';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const stages=[{name:'New',statuses:['NOT_CONTACTED'],color:'lime'},{name:'Contacted',statuses:['ATTEMPTED','CONTACTED','REPLIED'],color:'cyan'},{name:'Follow-up',statuses:['FOLLOW_UP'],color:'violet'},{name:'Consultation',statuses:['CONSULTATION_SET'],color:'blue'}];
export default function SalesDashboard({campaign,onNavigate,onOpen}:{campaign:string;onNavigate:(p:string)=>void;onOpen:(p:QueueItem)=>void}){
 const [prospects,setProspects]=useState<Prospect[]|null>(null),[metrics,setMetrics]=useState<any>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[refresh,setRefresh]=useState(0),[mission,setMission]=useState<any>(null),[queue,setQueue]=useState<any>(null);
 useEffect(()=>{let active=true;setProspects(null);setMetrics(null);setMission(null);setQueue(null);setError('');setSearch('');setFilter('All');
 Promise.allSettled([api.prospects(campaign),api.metrics(campaign),api.followUps(campaign),api.momentum(),api.queue(campaign)]).then(([p,m,f,d,q])=>{if(!active)return;if(d.status==='fulfilled')setMission(d.value.mission);if(q.status==='fulfilled')setQueue(q.value);if(d.status==='rejected'||q.status==='rejected')setError('Today’s mission could not fully load. Please refresh.');if(p.status==='fulfilled'){const followups=new Map(f.status==='fulfilled'?f.value.map((row:any)=>[row.id,row] as const):[]);setProspects((p.value as Prospect[]).map(row=>({...row,next_action:(followups.get(row.prospect_id??row.id) as any)?.next_action})));}else setError('Prospects could not load. Please refresh.');if(m.status==='fulfilled')setMetrics(m.value);else setError(x=>x||'Revenue metrics could not load. Please refresh.');});return()=>{active=false};},[campaign,refresh]);
 const counts=stages.map(s=>prospects?.filter(p=>s.statuses.includes(p.sales_status||'NOT_CONTACTED')).length??0);
 const active=prospects?.filter(p=>!['BOOKED','NOT_INTERESTED'].includes(p.sales_status||'')).length;
 const priority=useMemo(()=>{const rank=(p:Prospect)=>p.sales_status==='FOLLOW_UP'?0:p.sales_status==='CONSULTATION_SET'?1:2;return (prospects||[]).filter(p=>!['BOOKED','NOT_INTERESTED'].includes(p.sales_status||'')).filter(p=>(filter==='All'||(filter==='Follow-up'?p.sales_status==='FOLLOW_UP':p.sales_status==='CONSULTATION_SET'))&&`${name(p)} ${p.city||''} ${p.email||''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>rank(a)-rank(b)||Number(b.score||0)-Number(a.score||0)).slice(0,6);},[prospects,search,filter]);
 const cards=[{title:'Active prospects',value:active,icon:'people',color:'lime',hint:'In this campaign'},{title:'Follow-ups',value:prospects?counts[2]:undefined,icon:'calendar',color:'violet',hint:'Awaiting your next move'},{title:'Consultations',value:prospects?counts[3]:undefined,icon:'sell',color:'cyan',hint:'Current consultation stage'},{title:'Booked revenue',value:metrics?money(Number(metrics.booked_revenue||0)):undefined,icon:'queue',color:'lime',hint:'Saved booked value'}];
 const bestLead=(queue?.daily_queue||[]).filter((p:any)=>!['BOOKED','NOT_INTERESTED'].includes(p.sales_status||'')).sort((a:any,b:any)=>Number(b.icp_score??b.score??0)-Number(a.icp_score??a.score??0))[0];
 const qualification=(p:any)=>{try{return p.qualification||JSON.parse(p.qualification_json||'{}')}catch{return {}}};
 return <div className="neo-dashboard kp-dashboard">
 <div className="neo-toolbar"><label className="neo-search"><Icon name="search"/><input aria-label="Search priority leads" placeholder="Search priority leads…" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{new Date().toLocaleDateString(undefined,{weekday:'short',month:'long',day:'numeric'})}</span><button aria-label="Refresh dashboard" onClick={()=>setRefresh(x=>x+1)}>↻</button></div>
 <section className="kp-mission-hero" aria-labelledby="mission-title">
 <div className="kp-mission-copy"><p className="xp-eyebrow">TODAY’S SALES MISSION</p><h2 id="mission-title">Make your next<br/>move count.</h2><p>{mission?.complete?'Your daily mission is complete. Keep your best conversations moving.':'Start the right conversation. Take one clear step forward.'}</p><button className="xp-primary kp-primary-action" onClick={()=>onNavigate('Up Next')}>Work my next lead <span aria-hidden="true">→</span></button>
 <div className="kp-mission-progress"><span>{mission?`${mission.contacts||0} of ${mission.contacts_target||8} contacts today`:'Loading today’s progress…'}</span><div role="progressbar" aria-label="Today’s sales mission" aria-valuemin={0} aria-valuemax={mission?.contacts_target||8} aria-valuenow={mission?.contacts||0}><i style={{transform:`scaleX(${Math.min(1,Number(mission?.contacts||0)/Math.max(1,Number(mission?.contacts_target||8)))})`}}/></div><small>{mission?mission.complete?'Mission complete ✓':`${mission.moves_remaining??Math.max(0,(mission.contacts_target||8)-(mission.contacts||0))} conversations to go`:'Your saved progress will appear here.'}</small></div></div>
 <article className="kp-featured-lead"><div className="kp-featured-top"><span>NEXT BEST LEAD</span><span>{bestLead?`${bestLead.icp_score??bestLead.score??'—'} MATCH`:'YOUR QUEUE'}</span></div><h3>{bestLead?name(bestLead):queue?'You’re caught up.':'Finding your next move…'}</h3><p className="muted">{bestLead?[bestLead.category,bestLead.city,bestLead.state].filter(Boolean).join(' · '):'Ranked by fit in your selected campaign.'}</p><div className="kp-next-action"><small>RECOMMENDED NEXT MOVE</small><p>{bestLead?qualification(bestLead).recommended_action||bestLead.route_reason||'Confirm the decision-maker and start a focused conversation.':queue?'Find new prospects or review your scheduled follow-ups.':'Your lead recommendation will appear here.'}</p></div>{bestLead?<button onClick={()=>onOpen(bestLead)}>Review lead <span aria-hidden="true">↗</span></button>:queue&&<button onClick={()=>onNavigate('Lead Generator')}>Find prospects →</button>}</article>
 </section>
 {error&&<p className="notice" role="alert">{error}</p>}
 <section className="neo-metrics" aria-label="Campaign sales metrics">{cards.map(c=><article className={`neo-stat neo-${c.color}`} key={c.title}><div><span className="neo-stat-icon"><Icon name={c.icon}/></span><h3>{c.title}</h3></div><strong>{c.value??'—'}</strong><small>{c.hint}</small><div className="neo-stat-line" aria-hidden="true"/></article>)}</section>
 <details className="kp-support"><summary>Campaign pipeline <span>View stage breakdown</span></summary><section className="neo-pipeline"><div><p className="xp-eyebrow">CAMPAIGN PIPELINE</p><strong>{active??'—'}</strong><h3>Open prospects</h3></div><div className="neo-stage-area"><div className="neo-stage-bar" aria-hidden="true">{stages.map((s,i)=><i key={s.name} className={`neo-${s.color}`} style={{flex:counts[i]||0.15,opacity:counts[i]?1:.25}}/>)}</div><div className="neo-stages">{stages.map((s,i)=><div key={s.name}><span className={`neo-dot neo-${s.color}`}/><span>{s.name}</span><b>{prospects?counts[i]:'—'}</b></div>)}</div></div></section></details>
 <section className="neo-priorities"><div className="neo-section-head"><h3>Today’s priority leads</h3><button onClick={()=>onNavigate('Prospects')}>View all <span aria-hidden="true">→</span></button></div><div className="neo-chips" role="group" aria-label="Priority lead stage">{['All','Follow-up','Consultation'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>
 {prospects===null?<p role="status" className="empty">{error?'Unable to load prospects.':'Loading your prospects…'}</p>:priority.length?<div className="neo-lead-list">{priority.map(p=><button className="neo-lead-row" key={p.prospect_id??p.id} onClick={()=>onOpen(p)}><span className="neo-avatar" aria-hidden="true">{name(p).slice(0,2).toUpperCase()}</span><span className="neo-business"><b>{name(p)}</b><small>{[p.city,p.state].filter(Boolean).join(', ')||p.email||'Contact details in lead profile'}</small></span><span className={`neo-status ${p.sales_status==='FOLLOW_UP'?'neo-violet':p.sales_status==='CONSULTATION_SET'?'neo-blue':'neo-cyan'}`}>{label(p.sales_status)}</span><span className="neo-score">{p.score!=null?`${p.score} / 100`:'Unscored'}</span><span aria-hidden="true">›</span></button>)}</div>:<div className="empty"><p>{search||filter!=='All'?'No prospects match this filter.':'Your next connection starts here.'}</p><button onClick={()=>onNavigate('Lead Generator')}>Find prospects →</button></div>}
 </section><details className="kp-support"><summary>Plan and grow <span>Calendar & prospect tools</span></summary><div className="neo-footer-grid"><section className="card neo-shortcuts"><p className="xp-eyebrow">BUILD YOUR MOMENTUM</p><h3>Keep moving.</h3><p className="muted">Find new prospects. Save the next step. Make the connection.</p>{[['Add Prospect','Add prospect','plus'],['Lead Generator','Find prospects','search'],['Calendar','Plan follow-ups','calendar']].map(([page,title,icon])=><button key={page} onClick={()=>onNavigate(page)}><Icon name={icon}/>{title}<span aria-hidden="true">→</span></button>)}</section><CalendarGrid onNavigate={page=>onNavigate(page==='Follow-Up / Schedule Hub'?'Calendar':page)}/></div></details>
 </div>
}
